export interface Question {
  theme: string;
  level: number;
  question: string;
  answer: string;
}

export const QUESTIONS: Question[] = [
  { theme: "Géographie", level: 1, question: "Quelle est la capitale de la France ?", answer: "Paris" },
  { theme: "Géographie", level: 1, question: "Quel est le plus grand océan ?", answer: "Océan Pacifique" },
  { theme: "Géographie", level: 2, question: "Quel est le pays le plus vaste du monde ?", answer: "Russie" },
  { theme: "Géographie", level: 2, question: "Combien de continents y a-t-il sur Terre ?", answer: "7" },
  { theme: "Géographie", level: 1, question: "Quel désert est le plus grand du monde ?", answer: "Sahara" },
  { theme: "Géographie", level: 2, question: "Quelle est la capitale de l'Espagne ?", answer: "Madrid" },
  { theme: "Géographie", level: 2, question: "Quel est le plus long fleuve du monde ?", answer: "Nil" },
  { theme: "Géographie", level: 3, question: "Quel est le plus haut sommet d'Afrique ?", answer: "Kilimandjaro" },
  { theme: "Géographie", level: 3, question: "Quel pays a la plus grande population ?", answer: "Chine" },
  { theme: "Géographie", level: 2, question: "Combien d'Etats compte les États-Unis ?", answer: "50" },
  { theme: "Géographie", level: 2, question: "Quel est le plus grand pays d'Afrique par superficie ?", answer: "Algérie" },
  { theme: "Géographie", level: 3, question: "Quelle est la capitale de l'Italie ?", answer: "Rome" },
  { theme: "Géographie", level: 2, question: "Quelle est la capitale de l'Allemagne ?", answer: "Berlin" },
  { theme: "Géographie", level: 3, question: "Quel fleuve traverse Paris ?", answer: "Seine" },
  { theme: "Géographie", level: 4, question: "Quelle montagne est la plus haute du monde ?", answer: "Everest" },
  { theme: "Géographie", level: 4, question: "Quelle est la capitale de l'Australie ?", answer: "Canberra" },
  { theme: "Géographie", level: 3, question: "Quel est le point culminant de l'Europe ?", answer: "Mont Elbrouz" },
  { theme: "Géographie", level: 5, question: "Quel est le plus grand pays d'Amérique du Sud ?", answer: "Brésil" },
  { theme: "Géographie", level: 4, question: "Quelle est la capitale du Canada ?", answer: "Ottawa" },
  { theme: "Géographie", level: 3, question: "Quel est le plus grand pays d'Amérique du Nord ?", answer: "Canada" },
  { theme: "Géographie", level: 4, question: "Quel est le plus long fleuve d'Amérique du Nord ?", answer: "Mississippi" },
  { theme: "Géographie", level: 3, question: "Dans quel pays se trouve la forêt amazonienne ?", answer: "Brésil" },
  { theme: "Géographie", level: 5, question: "Quelle est la plus grande île du monde ?", answer: "Groenland" },
  { theme: "Géographie", level: 4, question: "Quel est le pays le plus peuplé d'Afrique ?", answer: "Nigeria" },
  { theme: "Géographie", level: 4, question: "Quel pays a une frontière avec le plus de pays voisins ?", answer: "Chine" },
  { theme: "Géographie", level: 3, question: "Combien de pays y a-t-il en Afrique ?", answer: "54" },
  { theme: "Géographie", level: 5, question: "Quel est le plus grand lac d'eau douce en volume ?", answer: "Lac Baïkal" },
  { theme: "Géographie", level: 5, question: "Quel est le plus long fleuve d'Europe ?", answer: "Volga" },
  { theme: "Géographie", level: 5, question: "Quelle est la profondeur de la fosse des Mariannes (en mètres) ?", answer: "10994" },
  { theme: "Géographie", level: 6, question: "Quel océan borde l'Antarctique au sud-est ?", answer: "Océan Pacifique" },
  { theme: "Géographie", level: 6, question: "Quel pays d'Europe ne possède aucune côte maritime ?", answer: "Liechtenstein" },
  { theme: "Géographie", level: 6, question: "Quelle est la capitale de la Mongolie ?", answer: "Oulan-Bator" },
  { theme: "Géographie", level: 6, question: "Quel est le deuxième plus grand pays du monde par superficie ?", answer: "Canada" },
  { theme: "Géographie", level: 7, question: "Quel est le point le plus bas de la surface terrestre ?", answer: "Mer Morte" },
  { theme: "Géographie", level: 7, question: "Quelle est la capitale de la Nouvelle-Zélande ?", answer: "Wellington" },
  { theme: "Géographie", level: 7, question: "Quel pays a le plus de fuseaux horaires ?", answer: "France" },
  { theme: "Géographie", level: 7, question: "Quel détroit relie la mer Rouge à l'océan Indien ?", answer: "Bab al Mandeb" },
  { theme: "Géographie", level: 3, question: "Quel est le plus petit pays du monde ?", answer: "Vatican" },
  { theme: "Géographie", level: 6, question: "Quel détroit sépare la France de l'Angleterre ?", answer: "Pas de Calais" },
  { theme: "Géographie", level: 6, question: "Quel détroit relie l'océan Atlantique à la mer Méditerranée ?", answer: "Détroit de Gibraltar" },
  { theme: "Géographie", level: 5, question: "Quelle est la plus grande île de la Méditerranée ?", answer: "Sicile" },
  { theme: "Géographie", level: 5, question: "Quel est le plus petit océan du monde ?", answer: "Océan Arctique" },
  { theme: "Géographie", level: 5, question: "Quelle est la capitale de l'Inde ?", answer: "New Delhi" },
  { theme: "Géographie", level: 6, question: "Quel est le plus haut volcan actif du monde ?", answer: "Ojos del Salado" },
  { theme: "Géographie", level: 6, question: "Quelle est la plus haute capitale du monde ?", answer: "La Paz" },
  { theme: "Géographie", level: 7, question: "Quel est le plus grand archipel du monde ?", answer: "Indonésie" },
  { theme: "Géographie", level: 7, question: "Dans quel pays se trouve le mont Everest ?", answer: "Népal" },
  { theme: "Géographie", level: 7, question: "Quel océan borde le Brésil à l'est ?", answer: "Océan Atlantique" },
  { theme: "Géographie", level: 7, question: "Quel est le plus grand pays d'Amérique centrale ?", answer: "Nicaragua" },
  { theme: "Géographie", level: 8, question: "Quelle est la frontière naturelle entre les États-Unis et le Mexique ?", answer: "Rio Grande" },
  { theme: "Géographie", level: 8, question: "Quel est le plus haut sommet d'Amérique du Nord ?", answer: "Denali" },
  { theme: "Géographie", level: 8, question: "Combien de pays compte l'Asie ?", answer: "49" },
  { theme: "Géographie", level: 8, question: "Combien de pays compte l'Europe ?", answer: "44" },
  { theme: "Géographie", level: 9, question: "Quelle est la capitale de l'Azerbaïdjan ?", answer: "Bakou" },
  { theme: "Géographie", level: 9, question: "Quel pays a la plus grande superficie désertique ?", answer: "Algérie" },
  { theme: "Géographie", level: 9, question: "Quelle est la capitale de l'Arabie Saoudite ?", answer: "Riyad" },
  { theme: "Géographie", level: 9, question: "Quel est le plus grand archipel d'Europe ?", answer: "Norvège" },
  { theme: "Géographie", level: 9, question: "Quel est le pays le moins peuplé du monde ?", answer: "Vatican" },
  { theme: "Géographie", level: 10, question: "Quelle est la longueur approximative du tropique du Cancer en kilomètres ?", answer: "36000" },
  { theme: "Histoire", level: 1, question: "Qui a été le premier président des États-Unis ?", answer: "George Washington" },
  { theme: "Histoire", level: 1, question: "Quelle année a marqué le début de la Seconde Guerre mondiale ?", answer: "1939" },
  { theme: "Histoire", level: 1, question: "Qui a découvert l'Amérique en 1492 ?", answer: "Christophe Colomb" },
  { theme: "Histoire", level: 2, question: "Qui était Napoléon Bonaparte ?", answer: "Empereur français" },
  { theme: "Histoire", level: 1, question: "Quel événement a débuté en France en 1789 ?", answer: "Révolution française" },
  { theme: "Histoire", level: 1, question: "En quelle année l'homme a-t-il marché sur la Lune ?", answer: "1969" },
  { theme: "Histoire", level: 2, question: "Qui a été le premier homme à marcher sur la Lune ?", answer: "Neil Armstrong" },
  { theme: "Histoire", level: 2, question: "Quel pharaon a construit la Grande Pyramide de Khéops ?", answer: "Khéops" },
  { theme: "Histoire", level: 2, question: "Qui était le chef des armées allemandes pendant la Seconde Guerre mondiale ?", answer: "Adolf Hitler" },
  { theme: "Histoire", level: 2, question: "Qui a été la première femme pilote d'avion transatlantique ?", answer: "Amelia Earhart" },
  { theme: "Histoire", level: 3, question: "Quel roi de France a fondé l'Académie française ?", answer: "Louis XIII" },
  { theme: "Histoire", level: 3, question: "Quelle reine britannique a régné au XXe siècle ?", answer: "Elizabeth II" },
  { theme: "Histoire", level: 3, question: "Quelle tribu a résisté à Jules César en Gaule ?", answer: "Arvernes" },
  { theme: "Histoire", level: 3, question: "En quelle année la chute de Constantinople a-t-elle eu lieu ?", answer: "1453" },
  { theme: "Histoire", level: 3, question: "Quel était le nom du dirigeant soviétique pendant la guerre froide, successeur de Staline ?", answer: "Nikita Khrouchtchev" },
  { theme: "Histoire", level: 3, question: "Quel était le principal combat aérien lors de la bataille d'Angleterre ?", answer: "Blitz" },
  { theme: "Histoire", level: 4, question: "Qui était le dirigeant du Royaume-Uni pendant la Seconde Guerre mondiale ?", answer: "Winston Churchill" },
  { theme: "Histoire", level: 4, question: "Quel est le nom du premier ordinateur électronique créé en 1946 ?", answer: "ENIAC" },
  { theme: "Histoire", level: 4, question: "Quel empire a aboli le servage en 1861 ?", answer: "Empire russe" },
  { theme: "Histoire", level: 4, question: "Qui était la reine d'Angleterre lors de la Première Guerre mondiale ?", answer: "Victoria" },
  { theme: "Histoire", level: 5, question: "Où la Déclaration d'indépendance des États-Unis a-t-elle été signée ?", answer: "Philadelphie" },
  { theme: "Histoire", level: 5, question: "Quel empire perse a été conquis par Alexandre le Grand ?", answer: "Empire perse achéménide" },
  { theme: "Histoire", level: 5, question: "Quel général carthaginois a traversé les Alpes avec des éléphants ?", answer: "Hannibal" },
  { theme: "Histoire", level: 5, question: "Quel soldat français est devenu empereur en 1804 ?", answer: "Napoléon Ier" },
  { theme: "Histoire", level: 5, question: "En quelle année la Révolution russe a-t-elle eu lieu ?", answer: "1917" },
  { theme: "Histoire", level: 5, question: "Quel pays a lancé le premier satellite artificiel en 1957 ?", answer: "Union soviétique" },
  { theme: "Histoire", level: 5, question: "Quel homme a créé la psychanalyse au XXe siècle ?", answer: "Sigmund Freud" },
  { theme: "Histoire", level: 6, question: "Quel personnage historique a dit 'L'État, c'est moi' ?", answer: "Louis XIV" },
  { theme: "Histoire", level: 6, question: "Quel pays a connu la guerre civile entre 1936 et 1939 ?", answer: "Espagne" },
  { theme: "Histoire", level: 6, question: "En quelle année a eu lieu la chute de l'Empire romain d'Occident ?", answer: "476" },
  { theme: "Histoire", level: 6, question: "Quel peuple nomade a envahi l'Europe au Ve siècle ?", answer: "Huns" },
  { theme: "Histoire", level: 7, question: "Quel traité a mis fin à la Première Guerre mondiale ?", answer: "Traité de Versailles" },
  { theme: "Histoire", level: 7, question: "Quel est le nom de la guerre civile anglaise (1642-1651) ?", answer: "Guerre civile anglaise" },
  { theme: "Histoire", level: 7, question: "Qui a dirigé l'Empire romain après Jules César ?", answer: "Octave" },
  { theme: "Histoire", level: 7, question: "Quelle dynastie japonaise a régné de 1185 à 1333 ?", answer: "Kamakura" },
  { theme: "Histoire", level: 8, question: "Quelle est la date de l'assassinat de l'archiduc François-Ferdinand ?", answer: "1914" },
  { theme: "Histoire", level: 8, question: "Qui a dirigé l'URSS pendant la guerre froide après Khrouchtchev ?", answer: "Leonid Brejnev" },
  { theme: "Histoire", level: 8, question: "Quel homme politique français a instigué la Révolution française ?", answer: "Maximilien Robespierre" },
  { theme: "Histoire", level: 8, question: "Quel général français a remporté la bataille de Valmy ?", answer: "François Kellermann" },
  { theme: "Histoire", level: 9, question: "Quel est le nom de la dynastie régnante en Chine lors de la découverte de l'Amérique ?", answer: "Ming" },
  { theme: "Histoire", level: 9, question: "En quelle année l'Empire mongol a-t-il atteint sa taille maximale ?", answer: "1279" },
  { theme: "Histoire", level: 9, question: "Quel était le nom du premier président de la République française ?", answer: "Louis-Napoléon Bonaparte" },
  { theme: "Histoire", level: 9, question: "Quelle opération militaire allemande a débuté en juin 1941 ?", answer: "Opération Barbarossa" },
  { theme: "Histoire", level: 10, question: "Qui a écrit 'Le Prince' en 1513 ?", answer: "Machiavel" },
  { theme: "Histoire", level: 10, question: "Quel est l'événement ayant marqué la fin de la Guerre de Cent Ans ?", answer: "Prise de Bordeaux" },
  { theme: "Sciences", level: 1, question: "Quelle est la plus grande planète du système solaire ?", answer: "Jupiter" },
  { theme: "Sciences", level: 1, question: "Quel est l'organe principal du système nerveux central ?", answer: "Cerveau" },
  { theme: "Sciences", level: 1, question: "Quel est l'élément chimique dont le symbole est O ?", answer: "Oxygène" },
  { theme: "Sciences", level: 1, question: "De combien de planètes se compose le système solaire ?", answer: "8" },
  { theme: "Sciences", level: 2, question: "Qui a formulé la loi de la gravitation universelle ?", answer: "Isaac Newton" },
  { theme: "Sciences", level: 2, question: "Quelle est la vitesse approximative de la lumière dans le vide en km/s ?", answer: "300000" },
  { theme: "Sciences", level: 2, question: "Combien de chromosomes possède l'humain ?", answer: "46" },
  { theme: "Sciences", level: 2, question: "Quel est l'organe de la digestion situé dans la bouche ?", answer: "Dents" },
  { theme: "Sciences", level: 2, question: "Quel gaz est majoritaire dans l'atmosphère terrestre ?", answer: "Azote" },
  { theme: "Sciences", level: 3, question: "Quel est le plus grand organe du corps humain ?", answer: "Peau" },
  { theme: "Sciences", level: 3, question: "Quel est l'os le plus long du corps humain ?", answer: "Fémur" },
  { theme: "Sciences", level: 3, question: "Quel métal alcalin est le plus léger ?", answer: "Lithium" },
  { theme: "Sciences", level: 3, question: "Quel est l'acide présent dans l'estomac ?", answer: "Acide chlorhydrique" },
  { theme: "Sciences", level: 3, question: "Quel scientifique est connu pour la théorie de la relativité restreinte ?", answer: "Einstein" },
  { theme: "Sciences", level: 4, question: "Quel instrument mesure la pression atmosphérique ?", answer: "Baromètre" },
  { theme: "Sciences", level: 4, question: "Quel est le principal composant du noyau des étoiles ?", answer: "Hydrogène" },
  { theme: "Sciences", level: 4, question: "Quel est le gaz à effet de serre le plus abondant ?", answer: "Dioxyde de carbone" },
  { theme: "Sciences", level: 4, question: "Quel est le symbole chimique du sodium ?", answer: "Na" },
  { theme: "Sciences", level: 4, question: "Quel est le principal minéral du corps humain en masse ?", answer: "Calcium" },
  { theme: "Sciences", level: 5, question: "Quelle est la plus petite unité de la vie ?", answer: "Cellule" },
  { theme: "Sciences", level: 5, question: "Quelle particule subatomique porte une charge positive ?", answer: "Proton" },
  { theme: "Sciences", level: 5, question: "Quel type de liaison chimique implique un partage d'électrons ?", answer: "Covalent" },
  { theme: "Sciences", level: 5, question: "Quel élément chimique est liquide à température ambiante ?", answer: "Mercure" },
  { theme: "Sciences", level: 5, question: "Quel organe produit l'insuline dans le corps humain ?", answer: "Pancréas" },
  { theme: "Sciences", level: 6, question: "Quel type de molécule est constituée d'acides aminés ?", answer: "Protéine" },
  { theme: "Sciences", level: 6, question: "Quel est le principe de base de la thermodynamique concernant l'énergie totale d'un système isolé ?", answer: "Conservation de l'énergie" },
  { theme: "Sciences", level: 6, question: "Quel est l'unité de base de la charge électrique ?", answer: "Coulomb" },
  { theme: "Sciences", level: 6, question: "Quel est le gaz incolore majoritairement présent dans l'air que nous respirons ?", answer: "Azote" },
  { theme: "Sciences", level: 7, question: "Quel est le modèle standard des particules en physique ?", answer: "Théorie des quarks" },
  { theme: "Sciences", level: 7, question: "Quelle est la théorie de Darwin sur l'origine des espèces ?", answer: "Évolution" },
  { theme: "Sciences", level: 7, question: "Quel organe humain pèse environ 1,5 kg ?", answer: "Cerveau" },
  { theme: "Sciences", level: 7, question: "Quelle loi décrit la chute libre des corps ?", answer: "Loi de la gravité" },
  { theme: "Sciences", level: 7, question: "Quel est le métal le plus conducteur d'électricité ?", answer: "Argent" },
  { theme: "Sciences", level: 8, question: "Quel élément chimique a pour symbole Au ?", answer: "Or" },
  { theme: "Sciences", level: 8, question: "Quelle particule élémentaire n'a pas de charge électrique ?", answer: "Neutron" },
  { theme: "Sciences", level: 8, question: "Comment nomme-t-on la période de révolution d'une planète ?", answer: "Année" },
  { theme: "Sciences", level: 8, question: "Quel animal est utilisé comme modèle génétique avec drosophile ?", answer: "Mouche" },
  { theme: "Sciences", level: 8, question: "Quelle molécule porte le code génétique ?", answer: "ADN" },
  { theme: "Sciences", level: 9, question: "Quel est le nombre d'éléments dans le système périodique de Mendeleïev ?", answer: "118" },
  { theme: "Sciences", level: 9, question: "Quelle est la constante de Planck (approximative) en J·s ?", answer: "6.626e-34" },
  { theme: "Sciences", level: 9, question: "Comment nomme-t-on la période de disparition massive des espèces il y a 66 millions d'années ?", answer: "Crétacé" },
  { theme: "Sciences", level: 9, question: "Quel organe assure la vision chez les insectes ?", answer: "Œil composé" },
  { theme: "Sciences", level: 10, question: "Quel isomère du glucose n'est pas métabolisé par l'homme ?", answer: "Cellobiose" },
  { theme: "Sciences", level: 10, question: "Quel physicien a démontré la relativité générale en 1915 ?", answer: "Albert Einstein" },
  { theme: "Cinéma", level: 1, question: "Qui a réalisé le film 'Jaws' (Les Dents de la mer) ?", answer: "Steven Spielberg" },
  { theme: "Cinéma", level: 1, question: "Quel film d'animation met en scène un jouet cowboy nommé Woody ?", answer: "Toy Story" },
  { theme: "Cinéma", level: 1, question: "Quel film de Tim Burton met en scène deux squelettes amoureux ?", answer: "Les Noces funèbres" },
  { theme: "Cinéma", level: 2, question: "Quel film de 1994 raconte la vie de Forrest Gump ?", answer: "Forrest Gump" },
  { theme: "Cinéma", level: 2, question: "Quel film se déroule dans un parc peuplé de dinosaures recréés génétiquement ?", answer: "Jurassic Park" },
  { theme: "Cinéma", level: 2, question: "Quel film de Christopher Nolan a pour personnage principal un homme qui traverse les rêves ?", answer: "Inception" },
  { theme: "Cinéma", level: 2, question: "Quel film de James Cameron a remporté 11 Oscars en 1998 ?", answer: "Titanic" },
  { theme: "Cinéma", level: 3, question: "Quel acteur interprète Jack Dawson dans 'Titanic' ?", answer: "Leonardo DiCaprio" },
  { theme: "Cinéma", level: 3, question: "Quelle actrice incarne Hermione Granger dans les films Harry Potter ?", answer: "Emma Watson" },
  { theme: "Cinéma", level: 3, question: "Qui a joué le rôle de Tony Stark (Iron Man) dans les films Marvel ?", answer: "Robert Downey Jr." },
  { theme: "Cinéma", level: 3, question: "Quel réalisateur a mis en scène 'Pulp Fiction' ?", answer: "Quentin Tarantino" },
  { theme: "Cinéma", level: 4, question: "Quel film a pour saga 'La Guerre des étoiles' ?", answer: "Star Wars" },
  { theme: "Cinéma", level: 4, question: "Quel film d'animation Pixar raconte l'histoire de deux monstres dans une usine de portes ?", answer: "Monstres & Cie" },
  { theme: "Cinéma", level: 4, question: "Quel film de Steven Spielberg met en scène un extraterrestre nommé E.T. ?", answer: "E.T. l'extra-terrestre" },
  { theme: "Cinéma", level: 4, question: "Quel film de Stanley Kubrick se déroule dans l'espace et met en scène l'intelligence artificielle HAL 9000 ?", answer: "2001, l'Odyssée de l'espace" },
  { theme: "Cinéma", level: 5, question: "Quel réalisateur a dirigé la trilogie du 'Seigneur des Anneaux' ?", answer: "Peter Jackson" },
  { theme: "Cinéma", level: 5, question: "Quel film français muet de 1927 est célèbre pour sa scène finale à la gare ?", answer: "Le Train" },
  { theme: "Cinéma", level: 5, question: "Quel film a mis en scène la chorégraphie de 'Thriller' de Michael Jackson ?", answer: "Thriller" },
  { theme: "Cinéma", level: 5, question: "Quel acteur a incarné James Bond dans le film 'Goldfinger' ?", answer: "Sean Connery" },
  { theme: "Cinéma", level: 6, question: "Quel film a remporté la Palme d'Or à Cannes en 2019 ?", answer: "Parasite" },
  { theme: "Cinéma", level: 6, question: "Qui a joué le rôle principal dans la saga 'Mission: Impossible' (agent Ethan Hunt) ?", answer: "Tom Cruise" },
  { theme: "Cinéma", level: 6, question: "Quel réalisateur français a réalisé 'Le Fabuleux Destin d'Amélie Poulain' ?", answer: "Jean-Pierre Jeunet" },
  { theme: "Cinéma", level: 7, question: "Qui a joué le Joker dans le film 'The Dark Knight' (2008) ?", answer: "Heath Ledger" },
  { theme: "Cinéma", level: 7, question: "Quel film de Fritz Lang de 1927 est une représentation dystopique de l'avenir ?", answer: "Metropolis" },
  { theme: "Cinéma", level: 8, question: "Quel film de science-fiction de 1982 met en scène des androïdes et des réplicants ?", answer: "Blade Runner" },
  { theme: "Cinéma", level: 8, question: "Quel cinéaste polonais a réalisé 'Le Pianiste' (2002) et 'La Liste de Schindler' (1993) ?", answer: "Roman Polanski" },
  { theme: "Cinéma", level: 8, question: "Quel film d'animation Studio Ghibli suit les aventures d'une sorcière et son chat ?", answer: "Kiki la petite sorcière" },
  { theme: "Cinéma", level: 9, question: "Quel long métrage a popularisé l'expression 'I'll be back' ?", answer: "Terminator" },
  { theme: "Cinéma", level: 9, question: "Quel film noir de 1941 met en scène Humphrey Bogart comme détective cynique ?", answer: "Le Faucon maltais" },
  { theme: "Cinéma", level: 9, question: "Qui a composé la bande originale de 'Star Wars' ?", answer: "John Williams" },
  { theme: "Cinéma", level: 10, question: "Quel film muet de 1928 réalisé par Carl Theodor Dreyer dépeint le procès de Jeanne d'Arc ?", answer: "La Passion de Jeanne d'Arc" },
  { theme: "Musique", level: 1, question: "Qui a chanté 'Ne me quitte pas' en 1959 ?", answer: "Jacques Brel" },
  { theme: "Musique", level: 1, question: "Quel groupe a chanté 'Bohemian Rhapsody' ?", answer: "Queen" },
  { theme: "Musique", level: 1, question: "Qui a composé la Symphonie n°9 (Ode à la Joie) ?", answer: "Beethoven" },
  { theme: "Musique", level: 1, question: "Qui est l'auteur-compositeur de la chanson 'Imagine' ?", answer: "John Lennon" },
  { theme: "Musique", level: 2, question: "Quel musicien est connu comme le roi de la pop ?", answer: "Michael Jackson" },
  { theme: "Musique", level: 2, question: "Quel est le nom du chanteur principal du groupe U2 ?", answer: "Bono" },
  { theme: "Musique", level: 3, question: "Quel compositeur autrichien a écrit 'La Flûte enchantée' ?", answer: "Mozart" },
  { theme: "Musique", level: 3, question: "Qui est le leader du groupe The Rolling Stones ?", answer: "Mick Jagger" },
  { theme: "Musique", level: 3, question: "Quel genre musical africain est à l'origine du jazz ?", answer: "Blues" },
  { theme: "Musique", level: 4, question: "Quel guitariste est célèbre pour avoir joué dans le groupe Queen ?", answer: "Brian May" },
  { theme: "Musique", level: 4, question: "Quelle chanteuse est connue pour l'album 'Like a Virgin' ?", answer: "Madonna" },
  { theme: "Musique", level: 4, question: "Qui a composé le Boléro ?", answer: "Maurice Ravel" },
  { theme: "Musique", level: 4, question: "Quel compositeur a écrit 'Le Lac des cygnes' ?", answer: "Piotr Ilitch Tchaïkovski" },
  { theme: "Musique", level: 5, question: "Quel compositeur baroque a écrit 'Les Quatre Saisons' ?", answer: "Vivaldi" },
  { theme: "Musique", level: 5, question: "Quel est le pays d'origine du tango ?", answer: "Argentine" },
  { theme: "Musique", level: 5, question: "Quel musicien est surnommé le roi du blues ?", answer: "Robert Johnson" },
  { theme: "Musique", level: 5, question: "Quel groupe a sorti l'album 'Abbey Road' ?", answer: "The Beatles" },
  { theme: "Musique", level: 6, question: "Quel bassiste des Beatles a également joué sur scène avec Toto ?", answer: "Paul McCartney" },
  { theme: "Musique", level: 6, question: "Quel genre musical est associé à Bob Marley ?", answer: "Reggae" },
  { theme: "Musique", level: 6, question: "Quel saxophoniste a popularisé le style jazz be-bop dans les années 1940 ?", answer: "Charlie Parker" },
  { theme: "Musique", level: 6, question: "Quel producteur a dirigé l'album 'Thriller' de Michael Jackson ?", answer: "Quincy Jones" },
  { theme: "Musique", level: 7, question: "Qui est considéré comme le père du blues ?", answer: "Robert Johnson" },
  { theme: "Musique", level: 7, question: "Quel compositeur français a écrit la musique de 'Peau d'âne' (film) ?", answer: "Michel Legrand" },
  { theme: "Musique", level: 7, question: "Quel festival de musique célèbre a eu lieu en 1969 aux États-Unis ?", answer: "Woodstock" },
  { theme: "Musique", level: 8, question: "Quel groupe britannique a interprété 'Stairway to Heaven' ?", answer: "Led Zeppelin" },
  { theme: "Sport", level: 1, question: "Quel pays a remporté la Coupe du monde de football en 2018 ?", answer: "France" },
  { theme: "Sport", level: 1, question: "Combien de joueurs par équipe au football ?", answer: "11" },
  { theme: "Sport", level: 1, question: "Combien de médailles d'or Michael Phelps a-t-il remportées ?", answer: "23" },
  { theme: "Sport", level: 1, question: "Qui détient le record du monde du 100 m nage libre ?", answer: "César Cielo" },
  { theme: "Sport", level: 1, question: "Quel sport se joue sur glace avec une rondelle ?", answer: "Hockey sur glace" },
  { theme: "Sport", level: 2, question: "Qui est surnommé 'la Pulga' en football ?", answer: "Lionel Messi" },
  { theme: "Sport", level: 2, question: "Quel pays a remporté la Coupe du monde de rugby en 2019 ?", answer: "Afrique du Sud" },
  { theme: "Sport", level: 2, question: "Quel sport est pratiqué dans le Stade de Wembley ?", answer: "Football" },
  { theme: "Sport", level: 2, question: "Combien d'heures dure un match de basket-ball professionnel ?", answer: "48" },
  { theme: "Sport", level: 3, question: "Quel athlète a remporté sept médailles d'or aux Jeux Olympiques de Pékin (2008) ?", answer: "Michael Phelps" },
  { theme: "Sport", level: 3, question: "Quel est le sport d'équipe avec 5 joueurs par équipe sur le terrain ?", answer: "Basket-ball" },
  { theme: "Sport", level: 3, question: "Quel cycliste a remporté le Tour de France à sept reprises ?", answer: "Lance Armstrong" },
  { theme: "Sport", level: 3, question: "Quel est le sport qui utilise une balle jaune fluo sur gazon ou terre battue ?", answer: "Tennis" },
  { theme: "Sport", level: 4, question: "Quel sportif a remporté le plus de titres en Formule 1 ?", answer: "Michael Schumacher" },
  { theme: "Sport", level: 4, question: "Quel pays a remporté le plus de Coupes du monde de football ?", answer: "Brésil" },
  { theme: "Sport", level: 4, question: "Quel est le plus grand stade de football du monde ?", answer: "Maracanã" },
  { theme: "Sport", level: 4, question: "Quel club de football italien a remporté le plus de titres de Serie A ?", answer: "Juventus" },
  { theme: "Sport", level: 5, question: "Quel joueur de tennis a remporté le tournoi de Roland-Garros le plus grand nombre de fois ?", answer: "Rafael Nadal" },
  { theme: "Sport", level: 5, question: "Quel est le record du monde du lancer du javelot masculin en mètres ?", answer: "98.48" },
  { theme: "Sport", level: 5, question: "Quel est le nom du maillot porté par le leader du Tour de France ?", answer: "Maillot jaune" },
  { theme: "Sport", level: 5, question: "Quel pilote automobile a remporté neuf titres de champion du monde de F1 ?", answer: "Lewis Hamilton" },
  { theme: "Sport", level: 6, question: "Quel club de football anglais a remporté le plus de titres en Premier League ?", answer: "Manchester United" },
  { theme: "Sport", level: 6, question: "Qui a remporté la NBA Finals en 2020 ?", answer: "Los Angeles Lakers" },
  { theme: "Sport", level: 6, question: "Combien de points vaut un essai en rugby ?", answer: "5" },
  { theme: "Sport", level: 7, question: "Quel est le record du monde du saut en longueur masculin en mètres ?", answer: "8.95" },
  { theme: "Sport", level: 7, question: "Quel joueur de football a remporté cinq Ballons d'Or ?", answer: "Lionel Messi" },
  { theme: "Sport", level: 7, question: "Quel est le nom du tour cycliste qui traverse toute la France en juillet ?", answer: "Tour de France" },
  { theme: "Sport", level: 7, question: "Quel coureur a remporté le plus de Grands Tours cyclistes ?", answer: "Eddy Merckx" },
  { theme: "Sport", level: 8, question: "Quelle équipe de baseball a remporté 27 titres de la Ligue majeure ?", answer: "New York Yankees" },
  { theme: "Sport", level: 8, question: "Qui détient le record du monde du 110 m haies ?", answer: "Aries Merritt" },
  { theme: "Sport", level: 8, question: "Quel est le record du monde du saut à la perche masculin en mètres ?", answer: "6.18" },
  { theme: "Sport", level: 8, question: "Quel joueur de tennis a remporté 23 titres du Grand Chelem en simple masculin ?", answer: "Novak Djokovic" },
  { theme: "Sport", level: 9, question: "Quel coureur cycliste a remporté cinq Tours d'Italie ?", answer: "Fausto Coppi" },
  { theme: "Sport", level: 9, question: "Quel est le record du monde du 400 m plat féminin en secondes ?", answer: "47.60" },
  { theme: "Sport", level: 9, question: "Quel est le sport le plus pratiqué au Brésil ?", answer: "Football" },
  { theme: "Sport", level: 9, question: "Quel est le plus grand événement sportif transnational d'Amérique du Sud ?", answer: "Copa América" },
  { theme: "Sport", level: 10, question: "Quel cycliste belge a remporté cinq Tours de France ?", answer: "Eddy Merckx" },
  { theme: "Littérature", level: 1, question: "Qui a écrit 'Le Petit Prince' ?", answer: "Antoine de Saint-Exupéry" },
  { theme: "Littérature", level: 1, question: "Qui a écrit 'Les Misérables' ?", answer: "Victor Hugo" },
  { theme: "Littérature", level: 1, question: "Quel auteur a créé le détective Sherlock Holmes ?", answer: "Arthur Conan Doyle" },
  { theme: "Littérature", level: 1, question: "Qui a écrit '1984' ?", answer: "George Orwell" },
  { theme: "Littérature", level: 2, question: "Quel écrivain français a écrit 'Madame Bovary' ?", answer: "Gustave Flaubert" },
  { theme: "Littérature", level: 2, question: "Qui a écrit 'À la recherche du temps perdu' ?", answer: "Marcel Proust" },
  { theme: "Littérature", level: 2, question: "Qui a écrit 'Robinson Crusoé' ?", answer: "Daniel Defoe" },
  { theme: "Littérature", level: 2, question: "Qui est l'auteur de 'Don Quichotte' ?", answer: "Miguel de Cervantes" },
  { theme: "Littérature", level: 3, question: "Qui a écrit 'Le Seigneur des anneaux' ?", answer: "J.R.R. Tolkien" },
  { theme: "Littérature", level: 3, question: "Quel poète français a écrit 'Les Fleurs du mal' ?", answer: "Charles Baudelaire" },
  { theme: "Littérature", level: 3, question: "Quel est l'auteur de 'Moby Dick' ?", answer: "Herman Melville" },
  { theme: "Littérature", level: 3, question: "Qui a écrit 'Bel-Ami' ?", answer: "Guy de Maupassant" },
  { theme: "Littérature", level: 4, question: "Qui a écrit 'Cyrano de Bergerac' ?", answer: "Edmond Rostand" },
  { theme: "Littérature", level: 4, question: "Qui a écrit la pièce 'Hamlet' ?", answer: "William Shakespeare" },
  { theme: "Littérature", level: 4, question: "Quel romancier russe est l'auteur de 'Crime et Châtiment' ?", answer: "Fiodor Dostoïevski" },
  { theme: "Littérature", level: 4, question: "Quel auteur américain a écrit 'Gatsby le Magnifique' ?", answer: "F Scott Fitzgerald" },
  { theme: "Littérature", level: 5, question: "Quel auteur français a écrit 'La Nausée' ?", answer: "Jean-Paul Sartre" },
  { theme: "Littérature", level: 5, question: "Qui a écrit 'La Divine Comédie' ?", answer: "Dante Alighieri" },
  { theme: "Littérature", level: 5, question: "Quel écrivain a écrit 'Ulysse' ?", answer: "James Joyce" },
  { theme: "Littérature", level: 5, question: "Qui a écrit 'Le Rouge et le Noir' ?", answer: "Stendhal" },
  { theme: "Littérature", level: 6, question: "Qui est l'auteur de la saga 'Harry Potter' ?", answer: "J.K. Rowling" },
  { theme: "Littérature", level: 6, question: "Quel poète grec a écrit 'L'Iliade' et 'L'Odyssée' ?", answer: "Homère" },
  { theme: "Littérature", level: 6, question: "Qui a écrit 'L'Étranger' ?", answer: "Albert Camus" },
  { theme: "Littérature", level: 6, question: "Quel écrivain a écrit 'Le Petit Prince' en 1943 ?", answer: "Antoine de Saint-Exupéry" },
  { theme: "Littérature", level: 7, question: "Quel écrivain britannique a écrit 'Le Seigneur des anneaux' ?", answer: "J.R.R. Tolkien" },
  { theme: "Littérature", level: 7, question: "Quel écrivain italien a écrit 'Le Nom de la Rose' ?", answer: "Umberto Eco" },
  { theme: "Littérature", level: 7, question: "Quel est le nom de l'auteur d''Orgueil et Préjugés' ?", answer: "Jane Austen" },
  { theme: "Littérature", level: 7, question: "Quel auteur a écrit 'Les Aventures de Tintin' ?", answer: "Hergé" },
  { theme: "Littérature", level: 8, question: "Quel conteur italien a écrit 'Pinocchio' ?", answer: "Carlo Collodi" },
  { theme: "Littérature", level: 8, question: "Quel poète romantique anglais a écrit 'Ode à un rossignol' ?", answer: "John Keats" },
  { theme: "Littérature", level: 8, question: "Quel écrivain français a écrit 'Tristram Shandy' ?", answer: "Laurence Sterne" },
  { theme: "Littérature", level: 9, question: "Qui est l'auteur du roman 'Le Médecin malgré lui' ?", answer: "Molière" },
  { theme: "Littérature", level: 9, question: "Quel auteur polonais a écrit 'Les Frères Karamazov' ?", answer: "Fiodor Dostoïevski" },
  { theme: "Littérature", level: 10, question: "Quel auteur a écrit 'La Métamorphose' ?", answer: "Franz Kafka" },
  { theme: "Littérature", level: 3, question: "Quel philosophe français du XVIIIe siècle a écrit 'Candide' ?", answer: "Voltaire" },
  { theme: "Littérature", level: 3, question: "Quel écrivain a écrit 'Le vieux et la mer' ?", answer: "Ernest Hemingway" },
  { theme: "Littérature", level: 3, question: "Qui a écrit 'Le Parfum' ?", answer: "Patrick Süskind" },
  { theme: "Littérature", level: 4, question: "Quel auteur a écrit 'Les Liaisons dangereuses' en 1782 ?", answer: "Choderlos de Laclos" },
  { theme: "Littérature", level: 4, question: "Qui a écrit 'Dracula' en 1897 ?", answer: "Bram Stoker" },
  { theme: "Littérature", level: 5, question: "Qui a écrit 'L'Alchimiste' en 1988 ?", answer: "Paulo Coelho" },
  { theme: "Littérature", level: 5, question: "Qui a écrit 'Au bonheur des ogres' ?", answer: "Daniel Pennac" },
  { theme: "Littérature", level: 6, question: "Quel auteur français a écrit 'Les Trois Mousquetaires' ?", answer: "Alexandre Dumas" },
  { theme: "Littérature", level: 6, question: "Quel écrivain argentin a écrit 'Le Zèbre' ?", answer: "Laurent Gaudé" },
  { theme: "Littérature", level: 7, question: "Quel écrivain a écrit 'Antigone' ?", answer: "Sophocle" },
  { theme: "Littérature", level: 8, question: "Quel roi a écrit une autobiographie intitulée 'Mémoires d'outre-tombe' ?", answer: "Chateaubriand" },
  { theme: "Littérature", level: 10, question: "Quel écrivain a fondé l'école réaliste en France au XIXe siècle ?", answer: "Flaubert" },
  { theme: "Littérature", level: 9, question: "Quel dramaturge anglais a écrit 'Roméo et Juliette' ?", answer: "William Shakespeare" },
  { theme: "Littérature", level: 5, question: "Qui a écrit 'Le Cid' ?", answer: "Pierre Corneille" },
  { theme: "Littérature", level: 4, question: "Qui a écrit 'Les Aventures de Tom Sawyer' ?", answer: "Mark Twain" },
  { theme: "Littérature", level: 4, question: "Qui a écrit 'Nana' ?", answer: "Émile Zola" },
  { theme: "Littérature", level: 4, question: "Qui a écrit 'Jane Eyre' ?", answer: "Charlotte Brontë" },
  { theme: "Littérature", level: 5, question: "Qui a écrit 'Don Quichotte' en espagnol ?", answer: "Miguel de Cervantes" },
  { theme: "Littérature", level: 3, question: "Qui a écrit 'Le Parfum' ?", answer: "Patrick Süskind" },
  { theme: "Littérature", level: 6, question: "Quel auteur français a écrit 'Le Château' ?", answer: "Franz Kafka" },
  { theme: "Art", level: 1, question: "Qui a peint la Mona Lisa (La Joconde) ?", answer: "Léonard de Vinci" },
  { theme: "Art", level: 1, question: "Quel peintre hollandais a coupé son oreille ?", answer: "Vincent van Gogh" },
  { theme: "Art", level: 1, question: "Qui est l'artiste principal associé au pop art avec les boîtes de soupe Campbell ?", answer: "Andy Warhol" },
  { theme: "Art", level: 2, question: "Qui a peint 'Guernica' en 1937 ?", answer: "Pablo Picasso" },
  { theme: "Art", level: 2, question: "Qui a sculpté 'Le Penseur' ?", answer: "Auguste Rodin" },
  { theme: "Art", level: 2, question: "Où se trouve le tableau 'La Joconde' ?", answer: "Louvre" },
  { theme: "Art", level: 2, question: "Qui a peint 'La Nuit étoilée' ?", answer: "Vincent van Gogh" },
  { theme: "Art", level: 3, question: "Qui a peint 'Le Déjeuner sur l'herbe' ?", answer: "Édouard Manet" },
  { theme: "Art", level: 3, question: "Qui a peint 'Le Radeau de la Méduse' ?", answer: "Théodore Géricault" },
  { theme: "Art", level: 3, question: "Qui a peint 'La Naissance de Vénus' ?", answer: "Sandro Botticelli" },
  { theme: "Art", level: 4, question: "Quel artiste a fondé le mouvement cubiste avec Picasso ?", answer: "Georges Braque" },
  { theme: "Art", level: 4, question: "Qui a peint 'Les Nymphéas' ?", answer: "Claude Monet" },
  { theme: "Art", level: 4, question: "Quel peintre a réalisé 'Le Cri' ?", answer: "Edvard Munch" },
  { theme: "Art", level: 5, question: "Quel peintre a peint les 'Tournesols' ?", answer: "Vincent van Gogh" },
  { theme: "Art", level: 5, question: "Quel artiste a peint 'Les Demoiselles d'Avignon' ?", answer: "Pablo Picasso" },
  { theme: "Art", level: 5, question: "Qui a peint 'Le Jardin des délices' ?", answer: "Hieronymus Bosch" },
  { theme: "Art", level: 6, question: "Qui a sculpté la statue de David à Florence ?", answer: "Michel-Ange" },
  { theme: "Art", level: 6, question: "Qui a peint 'La liberté guidant le peuple' ?", answer: "Eugène Delacroix" },
  { theme: "Art", level: 6, question: "Quel est le style artistique de Jackson Pollock ?", answer: "Expressionnisme abstrait" },
  { theme: "Art", level: 7, question: "Quel artiste a peint 'La tentation de Saint Antoine' en 1946 ?", answer: "Salvador Dali" },
  { theme: "Art", level: 7, question: "Qui est l'artiste majeur du surréalisme avec 'Le Père éternel' ?", answer: "Salvador Dali" },
  { theme: "Art", level: 8, question: "Quel architecte a conçu la tour Eiffel ?", answer: "Gustave Eiffel" },
  { theme: "Art", level: 8, question: "Qui a dessiné la Cène sur le mur du couvent Santa Maria delle Grazie ?", answer: "Léonard de Vinci" },
  { theme: "Art", level: 8, question: "Quel peintre français est l'auteur de 'La Cathédrale de Rouen' (série) ?", answer: "Claude Monet" },
  { theme: "Art", level: 9, question: "Qui a réalisé le plafond de la chapelle Sixtine à Rome ?", answer: "Michel-Ange" },
  { theme: "Art", level: 9, question: "Quel artiste a peint 'Le Fils de l'homme', montrant une pomme devant le visage ?", answer: "René Magritte" },
  { theme: "Art", level: 9, question: "Qui a peint 'La Ronde de nuit' en 1642 ?", answer: "Rembrandt" },
  { theme: "Art", level: 10, question: "Quel sculpteur italien est l'auteur du 'David' et de la 'Pietà' au Vatican ?", answer: "Michel-Ange" },
  { theme: "Art", level: 2, question: "Qui a peint 'La série Les Meules' (meules de foin) en 1890-1891 ?", answer: "Claude Monet" },
  { theme: "Art", level: 3, question: "Quel peintre américain a fondé le mouvement expressionniste abstrait ?", answer: "Jackson Pollock" },
  { theme: "Art", level: 3, question: "Quel architecte espagnol a conçu la Sagrada Família à Barcelone ?", answer: "Antoni Gaudí" },
  { theme: "Art", level: 5, question: "Quel peintre français est célèbre pour ses scènes de ballet à l'Opéra ?", answer: "Edgar Degas" },
  { theme: "Art", level: 5, question: "Qui a peint 'American Gothic' en 1930 ?", answer: "Grant Wood" },
  { theme: "Art", level: 5, question: "Quel peintre italien a peint 'Vieillard au violon' ? ", answer: "Marc Chagall" },
  { theme: "Art", level: 6, question: "Quel mouvement artistique est caractérisé par des couleurs vives et des formes géométriques depuis 1910 ?", answer: "Fauvisme" },
  { theme: "Art", level: 6, question: "Quel peintre du XXe siècle a peint 'Campbell Soup Cans' ?", answer: "Andy Warhol" },
  { theme: "Art", level: 6, question: "Quel architecte américain a conçu le musée du Louvre (pyramide) ?", answer: "I. M. Pei" },
  { theme: "Art", level: 7, question: "Quel peintre a réalisé 'Blue Poles' en 1952 ?", answer: "Jackson Pollock" },
  { theme: "Art", level: 7, question: "Qui a peint 'Les Montagnes Bleues' en 1905 ?", answer: "Gustav Klimt" },
  { theme: "Art", level: 8, question: "Quel mouvement artistique associe photomontage et idéaux révolutionnaires ?", answer: "Dadaïsme" },
  { theme: "Art", level: 9, question: "Quel peintre français a peint 'Le Déjeuner des canotiers' en 1881 ?", answer: "Pierre-Auguste Renoir" },
  { theme: "Art", level: 9, question: "Quel artiste est cofondateur du mouvement cubiste avec Picasso ?", answer: "Georges Braque" },
  { theme: "Art", level: 9, question: "Qui a peint 'La Forêt de Fontainebleau' en 1884 ?", answer: "Claude Monet" },
  { theme: "Art", level: 10, question: "Quel peintre américain a peint 'Nighthawks' en 1942 ?", answer: "Edward Hopper" },
  { theme: "Gastronomie", level: 1, question: "Quel fruit est principalement utilisé pour faire un guacamole ?", answer: "Avocat" },
  { theme: "Gastronomie", level: 1, question: "Quel fromage français est bleu et fabriqué avec du lait de brebis ?", answer: "Roquefort" },
  { theme: "Gastronomie", level: 1, question: "Quelle boisson alcoolisée est produite à partir de raisin fermenté ?", answer: "Vin" },
  { theme: "Gastronomie", level: 1, question: "Quel plat italien est à base de riz et de bouillon ?", answer: "Risotto" },
  { theme: "Gastronomie", level: 2, question: "Quelle épice est utilisée pour colorer un curry en jaune ?", answer: "Curcuma" },
  { theme: "Gastronomie", level: 2, question: "Quel aliment sert de base à la choucroute ?", answer: "Chou" },
  { theme: "Gastronomie", level: 2, question: "Quel produit laiterie est caillé puis égoutté pour faire du fromage ?", answer: "Caillé" },
  { theme: "Gastronomie", level: 2, question: "Quelle herbe aromatique est utilisée dans le tzatzíki grec ?", answer: "Menthe" },
  { theme: "Gastronomie", level: 3, question: "Quelle boisson se sert traditionnellement avec des sushis ?", answer: "Saké" },
  { theme: "Gastronomie", level: 3, question: "Quel alcool provient de la distillation de la pomme en Normandie ?", answer: "Calvados" },
  { theme: "Gastronomie", level: 3, question: "Quel aliment est fermenté pour obtenir du yaourt ?", answer: "Lait" },
  { theme: "Gastronomie", level: 4, question: "Quel fromage est traditionnellement préparé avec du lait de vache, fabriqué en Normandie ?", answer: "Camembert" },
  { theme: "Gastronomie", level: 4, question: "Quel plat français est préparé avec des œufs, de la crème et du gruyère ?", answer: "Quiche lorraine" },
  { theme: "Gastronomie", level: 4, question: "Quel est le nom du pain rond traditionnel de San Francisco ?", answer: "Sourdough" },
  { theme: "Gastronomie", level: 4, question: "Quelle boisson alcoolisée est obtenue par distillation du vin ?", answer: "Eau-de-vie" },
  { theme: "Gastronomie", level: 5, question: "Quel légume est la base de la piperade basque ?", answer: "Piment" },
  { theme: "Gastronomie", level: 5, question: "Quel fromage est utilisé pour faire de la raclette ?", answer: "Beaufort" },
  { theme: "Gastronomie", level: 5, question: "Quel cocktail contient du rhum, du citron vert et de la menthe ?", answer: "Mojito" },
  { theme: "Gastronomie", level: 5, question: "Quel plat indien est un curry traditionnel de pois chiches ?", answer: "Chana masala" },
  { theme: "Gastronomie", level: 6, question: "Quel fromage français a la forme d'un cône recouvert de cendre ?", answer: "Valençay" },
  { theme: "Gastronomie", level: 6, question: "Quel légume est l'ingrédient principal du houmous ?", answer: "Pois chiche" },
  { theme: "Gastronomie", level: 6, question: "Quel dessert italien est composé principalement de mascarpone et de café ?", answer: "Tiramisu" },
  { theme: "Gastronomie", level: 7, question: "Quel fruit est essentiel dans la préparation d'une tarte tatin ?", answer: "Pomme" },
  { theme: "Gastronomie", level: 7, question: "Quelle épice est extraite des graines de pistils rouges séchés ?", answer: "Safran" },
  { theme: "Gastronomie", level: 7, question: "Quel aliment est utilisé pour épaissir les soupes à l'oignon ?", answer: "Baguette" },
  { theme: "Gastronomie", level: 8, question: "Quel fromage suisse est utilisé pour le fondue moitié-moitié ?", answer: "Gruyère" },
  { theme: "Gastronomie", level: 8, question: "Quel vin champenois est connu pour ses fines bulles ?", answer: "Champagne" },
  { theme: "Gastronomie", level: 8, question: "Quelle céréale est utilisée comme base dans le couscous ?", answer: "Semoule" },
  { theme: "Gastronomie", level: 8, question: "Quel condiment asiatique est fabriqué à partir de haricots fermentés ?", answer: "Miso" },
  { theme: "Gastronomie", level: 9, question: "Quel type de vin est élaboré sans fermentation alcoolique du jus ?", answer: "Vin de noix" },
  { theme: "Gastronomie", level: 9, question: "Quel fromage de chèvre français est recouvert de cendres ?", answer: "Valençay" },
  { theme: "Gastronomie", level: 9, question: "Quel est l'ingrédient principal du moutabal (caviar d'aubergine) ?", answer: "Aubergine" },
  { theme: "Gastronomie", level: 10, question: "Quel fromage de Savoie est affiné en grottes naturelles ?", answer: "Beaufort" },
  { theme: "Gastronomie", level: 4, question: "Quel fromage grec est préparé avec du lait de brebis et du sel ?", answer: "Feta" },
  { theme: "Gastronomie", level: 4, question: "Quel alcool est obtenu par distillation du jus de canne à sucre ?", answer: "Rhum" },
  { theme: "Gastronomie", level: 4, question: "Quel plat japonais consiste en poisson cru et riz vinaigré ?", answer: "Sushi" },
  { theme: "Gastronomie", level: 5, question: "Quel fruit tropical est à l'origine du jus d'ananas ?", answer: "Ananas" },
  { theme: "Gastronomie", level: 5, question: "Quelle herbe entre dans la composition d'un pesto traditionnel ?", answer: "Basilic" },
  { theme: "Gastronomie", level: 5, question: "Quel légume constitue la base du ragoût alsacien choucroute ?", answer: "Chou" },
  { theme: "Gastronomie", level: 6, question: "Quel fromage suisse est reconnaissable à ses trous ?", answer: "Emmental" },
  { theme: "Gastronomie", level: 6, question: "Quel plat traditionnel marocain est à base de semoule, viande et légumes ?", answer: "Couscous" },
  { theme: "Gastronomie", level: 6, question: "Quel condiment japonais est à base de piments fermentés et d'ail ?", answer: "Sambal" },
  { theme: "Gastronomie", level: 6, question: "Quel fromage italien file traditionnellement quand il fond ?", answer: "Mozzarella" },
  { theme: "Gastronomie", level: 7, question: "Quel champignon est un ingrédient clé du boeuf bourguignon ?", answer: "Champignon" },
  { theme: "Gastronomie", level: 7, question: "Quel est le principal ingrédient de la soupe miso ?", answer: "Tofu" },
  { theme: "Gastronomie", level: 7, question: "Quel fruit est utilisé pour faire de la confiture de fraises ?", answer: "Fraise" },
  { theme: "Gastronomie", level: 7, question: "Quelle céréale est utilisée pour faire la bière ?", answer: "Orge" },
  { theme: "Gastronomie", level: 8, question: "Quel fromage italien est affiné en boule dans l'eau de mer ?", answer: "Mozzarella di Buffala" },
  { theme: "Gastronomie", level: 8, question: "Quel est le principal ingrédient du homous libanais ?", answer: "Pois chiche" },
  { theme: "Gastronomie", level: 9, question: "Quel aliment est nécessaire pour préparer des gnocchis ?", answer: "Pommes de terre" },
  { theme: "Gastronomie", level: 9, question: "Quel condiment asiatique est obtenu par fermentation de soja ?", answer: "Sauce soja" },
  { theme: "Gastronomie", level: 9, question: "Quel fruit rouge est souvent utilisé pour garnir les cheesecakes ?", answer: "Groseille" },
  { theme: "Gastronomie", level: 9, question: "Quel ingrédient est commun à la ratatouille et au gazpacho ?", answer: "Tomate" },
  { theme: "Politique", level: 1, question: "Qui est le président de la France en 2025 ?", answer: "Emmanuel Macron" },
  { theme: "Politique", level: 1, question: "Qui est le président des États-Unis en 2025 ?", answer: "Joe Biden" },
  { theme: "Politique", level: 1, question: "Quel pays a le plus grand nombre d'habitants ?", answer: "Chine" },
  { theme: "Politique", level: 1, question: "Qui est le secrétaire général actuel de l'ONU ?", answer: "Antonio Guterres" },
  { theme: "Politique", level: 2, question: "Quel pays est dirigé par Vladimir Poutine ?", answer: "Russie" },
  { theme: "Politique", level: 2, question: "Quel est le nom de la monnaie de l'Union européenne ?", answer: "Euro" },
  { theme: "Politique", level: 2, question: "Qui est la chancelière allemande la plus récente avant 2025 ?", answer: "Angela Merkel" },
  { theme: "Politique", level: 3, question: "Quelle est la capitale de l'Union européenne (de facto) ?", answer: "Bruxelles" },
  { theme: "Politique", level: 3, question: "Quel pays a le plus grand PIB mondial ?", answer: "États-Unis" },
  { theme: "Politique", level: 3, question: "Quel club de football italien a remporté le plus de titres de Serie A ?", answer: "Juventus" },
  { theme: "Politique", level: 4, question: "Quel traité a créé l'Union européenne ?", answer: "Traité de Maastricht" },
  { theme: "Politique", level: 4, question: "Qui est le dirigeant de la Chine en 2025 ?", answer: "Xi Jinping" },
  { theme: "Politique", level: 4, question: "Quel est le nom de la chambre basse du Parlement français ?", answer: "Assemblée nationale" },
  { theme: "Politique", level: 5, question: "Quelle est la capitale de la Roumanie ?", answer: "Bucarest" },
  { theme: "Politique", level: 5, question: "Quel pays européen a pour langue officielle le hongrois ?", answer: "Hongrie" },
  { theme: "Politique", level: 5, question: "Qui a été le premier président de la Ve République française ?", answer: "Charles de Gaulle" },
  { theme: "Politique", level: 6, question: "Quel est le nom du dirigeant en Corée du Nord ?", answer: "Kim Jong-un" },
  { theme: "Politique", level: 6, question: "Quel est le parti politique du Premier ministre indien actuel ?", answer: "Bharatiya Janata Party" },
  { theme: "Politique", level: 6, question: "Qui a aboli la peine de mort en France en 1981 ?", answer: "François Mitterrand" },
  { theme: "Politique", level: 6, question: "Qui est le roi actuel d'Espagne ?", answer: "F\u00e9lipe VI" },
  { theme: "Politique", level: 7, question: "Combien de d\u00e9put\u00e9s compte l'Assembl\u00e9e nationale fran\u00e7aise ?", answer: "577" },
  { theme: "Politique", level: 7, question: "Qui a \u00e9t\u00e9 le premier Pr\u00e9sident de la Ve R\u00e9publique fran\u00e7aise ?", answer: "Charles de Gaulle" },
  { theme: "Politique", level: 7, question: "Quel club de football italien a remporté le plus de titres de Serie A ?", answer: "Juventus" },
  { theme: "Politique", level: 8, question: "Quel est le seul pays d'Afrique du Nord sans monarchie ?", answer: "Tunisie" },
  { theme: "Politique", level: 8, question: "Combien de membres comptait l'Union europ\u00e9enne en 2020 ?", answer: "27" },
  { theme: "Politique", level: 9, question: "Quelle ville est le si\u00e8ge du Parlement europ\u00e9en ?", answer: "Strasbourg" },
  { theme: "Politique", level: 9, question: "Quelle est la capitale de la Turquie ?", answer: "Ankara" },
  { theme: "Politique", level: 10, question: "Quel ancien pr\u00e9sident fran\u00e7ais a \u00e9t\u00e9 li\u00e9 \u00e0 la lib\u00e9ration de la France en 1944 ?", answer: "Charles de Gaulle" },
  { theme: "Économie", level: 1, question: "Quelle est la monnaie officielle du Japon ?", answer: "Yen" },
  { theme: "Économie", level: 1, question: "Qu'est-ce que le PIB ?", answer: "Produit Int\u00e9rieur Brut" },
  { theme: "Économie", level: 2, question: "Quel pays a l'indice de corruption le plus bas selon Transparency International en 2021 ?", answer: "Danemark" },
  { theme: "Économie", level: 2, question: "Qu'est-ce que l'inflation ?", answer: "Augmentation des prix" },
  { theme: "Économie", level: 3, question: "Quelle est la place financiere principale de la France ?", answer: "Paris" },
  { theme: "Économie", level: 3, question: "Quel est le volume standard d'une colonne de monnaie ?", answer: "100" },
  { theme: "Économie", level: 4, question: "Quel est l'indice boursier principal de la France ?", answer: "CAC 40" },
  { theme: "Économie", level: 4, question: "Qu'est-ce qu'un budget excédentaire ?", answer: "Recettes sup\u00e9rieures aux d\u00e9penses" },
  { theme: "Économie", level: 5, question: "Quel est le pays producteur de cacao le plus important ?", answer: "C\u00f4te d'Ivoire" },
  { theme: "Économie", level: 5, question: "Quelle est la plan\u00e8te la plus priv\u00e9e de ressource ?", answer: "Mars" },
  { theme: "Économie", level: 6, question: "Quel est le pays le plus endett\u00e9 en valeur absolue ?", answer: "États-Unis" },
  { theme: "Économie", level: 6, question: "Quel est le taux de TVA en France (r\u00e9gime normal) ?", answer: "20%" },
  { theme: "Économie", level: 7, question: "Quelle a \u00e9t\u00e9 la date de la r\u00e9serve obligatoire des banques fran\u00e7aises en 2020 ?", answer: "13207" },
  { theme: "Économie", level: 7, question: "Quel est le terme pour le niveau g\u00e9n\u00e9ral des prix des biens et services ?", answer: "Indicateur de l'inflation" },
  { theme: "Économie", level: 8, question: "Quel pays est le plus gros exportateur d'or au monde ?", answer: "Chine" },
  { theme: "Économie", level: 8, question: "Quel indicateur \u00e9conomique mesure le flux de biens et services d'un pays vers l'\u00e9tranger ?", answer: "Exportations" },
  { theme: "Économie", level: 9, question: "Quelle est la banque centrale de l'Union europ\u00e9enne ?", answer: "Banque centrale europ\u00e9enne" },
  { theme: "Économie", level: 9, question: "Comment appelle-t-on la combinaison des dettes publiques cumul\u00e9es ?", answer: "Dette publique" },
  { theme: "Économie", level: 10, question: "Quelle est la pri\u00e8re de base de l'\u00e9conomie cr\u00e9ative ?", answer: "Innovation" },
  { theme: "Économie", level: 10, question: "Quel concept \u00e9conomique décrit un march\u00e9 avec une seule entreprise ?", answer: "Monopole" },
  { theme: "Culture populaire", level: 1, question: "Quel super-h\u00e9ros porte un bouclier aux couleurs de l'\u00c9tats-Unis ?", answer: "Captain America" },
  { theme: "Culture populaire", level: 1, question: "Quel jeu de soci\u00e9t\u00e9 consiste \u00e0 poser des questions pour deviner un mot ?", answer: "Jeu du Pendu" },
  { theme: "Culture populaire", level: 2, question: "Quel r\u00e9seau social est utilis\u00e9 pour partager des photos et des histoires ?", answer: "Instagram" },
  { theme: "Culture populaire", level: 2, question: "Quel est le sport pr\u00e9f\u00e9r\u00e9 de la France en termes d'audience t\u00e9l\u00e9visuelle ?", answer: "Football" },
  { theme: "Culture populaire", level: 3, question: "Quel est le nom de l'h\u00e9ros dans les films 'La Guerre des \u00e9toiles' ?", answer: "Luke Skywalker" },
  { theme: "Culture populaire", level: 3, question: "Quel est le nom de la chanteuse des Black Eyed Peas ?", answer: "Fergie" },
  { theme: "Culture populaire", level: 3, question: "Quel id\u00e9e de mode a lanc\u00e9 Serge Gainsbourg dans les ann\u00e9es 1980 ?", answer: "New Wave" },
  { theme: "Culture populaire", level: 4, question: "Quel est le nom du groupe de rock de 5 membres qui a enregistr\u00e9 'Bohemian Rhapsody' ?", answer: "Queen" },
  { theme: "Culture populaire", level: 4, question: "Quel personnage de BD est un petit hippopotame rose ?", answer: "Peluche" },
  { theme: "Culture populaire", level: 4, question: "Quel jeu vid\u00e9o culte a pour personnage principal Mario ?", answer: "Super Mario Bros" },
  { theme: "Culture populaire", level: 4, question: "Quel est le nom du chronom\u00e9trage officiel de la Coupe du monde de football ?", answer: "FIFA" },
  { theme: "Culture populaire", level: 5, question: "Quel auteur r\u00e9pute \u00e9cris 'It' et 'Le Fl\u00e9au' ?", answer: "Stephen King" },
  { theme: "Culture populaire", level: 5, question: "Quel est le style musical du groupe Nirvana ?", answer: "Grunge" },
  { theme: "Culture populaire", level: 6, question: "Quel est le nom du magicien blond avec une baguette dans les livres de JK Rowling ?", answer: "Harry Potter" },
  { theme: "Culture populaire", level: 7, question: "Quel est le titre du premier film de la saga 'Star Wars' en date de sortie ?", answer: "Un Nouvel Espoir" },
  { theme: "Culture populaire", level: 8, question: "Quel est le nom de l'auteur du roman 'Dune' ?", answer: "Frank Herbert" },
  { theme: "Culture populaire", level: 9, question: "Qui a jou\u00e9 le r\u00f4le principal dans le film 'Gladiator' ?", answer: "Russell Crowe" },
  { theme: "Culture populaire", level: 10, question: "Quel jeu v\u00e9d\u00e9o de 1985 est consid\u00e9r\u00e9 comme l'un des premiers jeux d'action-plateforme ?", answer: "Super Mario Bros" },
];
