export interface Question {
  theme: string;
  level: number;
  question: string;
  answer: string;
}

export const QUESTIONS: Question[] = [
  { theme: 'Géographie', level: 1, question: 'Quelle est la capitale de la France ?', answer: 'Paris' },
  { theme: 'Géographie', level: 1, question: 'Dans quel pays se trouve la ville de New York ?', answer: 'États-Unis' },
  { theme: 'Géographie', level: 2, question: 'Quel est le plus grand océan du monde ?', answer: 'Océan Pacifique' },
  { theme: 'Géographie', level: 2, question: 'Sur quel continent se trouve l\'Égypte ?', answer: 'Afrique' },
  { theme: 'Géographie', level: 3, question: 'Quelle est la capitale de l\'Espagne ?', answer: 'Madrid' },
  { theme: 'Géographie', level: 3, question: 'Quel pays a la forme d\'une botte ?', answer: 'Italie' },
  { theme: 'Géographie', level: 4, question: 'Quel fleuve traverse l\'Égypte ?', answer: 'Le Nil' },
  { theme: 'Géographie', level: 4, question: 'Quelle est la capitale du Canada ?', answer: 'Ottawa' },
  { theme: 'Géographie', level: 5, question: 'Dans quelle chaîne de montagnes se trouve le Mont Blanc ?', answer: 'Les Alpes' },
  { theme: 'Géographie', level: 5, question: 'Quel est le plus grand pays du monde par superficie ?', answer: 'Russie' },
  { theme: 'Géographie', level: 6, question: 'Quelle est la capitale de la Turquie ?', answer: 'Ankara' },
  { theme: 'Géographie', level: 6, question: 'Quel détroit sépare l\'Espagne du Maroc ?', answer: 'Le détroit de Gibraltar' },
  { theme: 'Géographie', level: 7, question: 'Quelle est la capitale du Brésil ?', answer: 'Brasilia' },
  { theme: 'Géographie', level: 7, question: 'Dans quel pays se trouve le Machu Picchu ?', answer: 'Pérou' },
  { theme: 'Géographie', level: 8, question: 'Quel est le fleuve le plus long d\'Asie ?', answer: 'Le Yangzi Jiang' },
  { theme: 'Géographie', level: 8, question: 'Quelle est la capitale du Kazakhstan ?', answer: 'Astana' },
  { theme: 'Géographie', level: 9, question: 'Quel est le point le plus bas de la Terre sur la terre ferme ?', answer: 'La mer Morte' },
  { theme: 'Géographie', level: 9, question: 'Quelle est la capitale du Burkina Faso ?', answer: 'Ouagadougou' },
  { theme: 'Géographie', level: 10, question: 'Quelle île, partagée entre trois pays, est la troisième plus grande du monde ?', answer: 'Bornéo' },
  { theme: 'Géographie', level: 10, question: 'Quel est le nom du détroit séparant la Russie de l\'Alaska ?', answer: 'Le détroit de Béring' },
  { theme: 'Histoire', level: 1, question: 'Qui a découvert l\'Amérique en 1492 ?', answer: 'Christophe Colomb' },
  { theme: 'Histoire', level: 1, question: 'Quel dictateur a dirigé l\'Allemagne nazie ?', answer: 'Adolf Hitler' },
  { theme: 'Histoire', level: 2, question: 'Quel empereur français a perdu la bataille de Waterloo ?', answer: 'Napoléon Bonaparte' },
  { theme: 'Histoire', level: 2, question: 'En quelle année a débuté la Première Guerre mondiale ?', answer: '1914' },
  { theme: 'Histoire', level: 3, question: 'Qui était le Roi-Soleil ?', answer: 'Louis XIV' },
  { theme: 'Histoire', level: 3, question: 'Quelle civilisation a construit les pyramides de Gizeh ?', answer: 'Les Égyptiens' },
  { theme: 'Histoire', level: 4, question: 'Quel mur est tombé en 1989 ?', answer: 'Le mur de Berlin' },
  { theme: 'Histoire', level: 4, question: 'Qui a été le premier président des États-Unis ?', answer: 'George Washington' },
  { theme: 'Histoire', level: 5, question: 'En quelle année l\'homme a-t-il marché sur la Lune ?', answer: '1969' },
  { theme: 'Histoire', level: 5, question: 'Quelle reine d\'Égypte a eu une liaison avec Jules César ?', answer: 'Cléopâtre' },
  { theme: 'Histoire', level: 6, question: 'Quel roi de France a été guillotiné en 1793 ?', answer: 'Louis XVI' },
  { theme: 'Histoire', level: 6, question: 'Quelle guerre a opposé le Nord et le Sud des États-Unis ?', answer: 'La guerre de Sécession' },
  { theme: 'Histoire', level: 7, question: 'Qui a prononcé le discours "I have a dream" ?', answer: 'Martin Luther King' },
  { theme: 'Histoire', level: 7, question: 'Quel traité a mis fin à la Première Guerre mondiale ?', answer: 'Le traité de Versailles' },
  { theme: 'Histoire', level: 8, question: 'En quelle année a eu lieu la chute de l\'Empire romain d\'Occident ?', answer: '476' },
  { theme: 'Histoire', level: 8, question: 'Quel explorateur portugais a ouvert la route des Indes en 1498 ?', answer: 'Vasco de Gama' },
  { theme: 'Histoire', level: 9, question: 'Qui était le président de l\'URSS lors de sa dissolution en 1991 ?', answer: 'Mikhaïl Gorbatchev' },
  { theme: 'Histoire', level: 9, question: 'Quelle bataille navale de 1805 a vu la victoire de Nelson ?', answer: 'Trafalgar' },
  { theme: 'Histoire', level: 10, question: 'Quel roi de Babylone est célèbre pour son code de lois ?', answer: 'Hammurabi' },
  { theme: 'Histoire', level: 10, question: 'Quelle guerre a duré de 1337 à 1453 ?', answer: 'La guerre de Cent Ans' },
  { theme: 'Cinéma', level: 1, question: 'Quel super-héros porte un costume d\'araignée ?', answer: 'Spider-Man' },
  { theme: 'Cinéma', level: 1, question: 'Dans quel film trouve-t-on un ogre vert nommé Shrek ?', answer: 'Shrek' },
  { theme: 'Cinéma', level: 2, question: 'Quel acteur joue Jack Dawson dans Titanic ?', answer: 'Leonardo DiCaprio' },
  { theme: 'Cinéma', level: 2, question: 'Quel est le nom du lion dans Le Roi Lion ?', answer: 'Simba' },
  { theme: 'Cinéma', level: 3, question: 'Quel agent secret porte le matricule 007 ?', answer: 'James Bond' },
  { theme: 'Cinéma', level: 3, question: 'Quel film commence par "Il y a bien longtemps, dans une galaxie lointaine..." ?', answer: 'Star Wars' },
  { theme: 'Cinéma', level: 4, question: 'Qui a réalisé E.T. l\'extra-terrestre ?', answer: 'Steven Spielberg' },
  { theme: 'Cinéma', level: 4, question: 'Quel est le prénom du sorcier joué par Daniel Radcliffe ?', answer: 'Harry' },
  { theme: 'Cinéma', level: 5, question: 'Quelle actrice incarne Katniss Everdeen dans Hunger Games ?', answer: 'Jennifer Lawrence' },
  { theme: 'Cinéma', level: 5, question: 'Dans quel film entend-on la réplique "Je suis ton père" ?', answer: 'L\'Empire contre-attaque' },
  { theme: 'Cinéma', level: 6, question: 'Qui a réalisé le film Pulp Fiction ?', answer: 'Quentin Tarantino' },
  { theme: 'Cinéma', level: 6, question: 'Quel film a remporté l\'Oscar du meilleur film en 2020 (film sud-coréen) ?', answer: 'Parasite' },
  { theme: 'Cinéma', level: 7, question: 'Quel acteur incarne le Joker dans The Dark Knight ?', answer: 'Heath Ledger' },
  { theme: 'Cinéma', level: 7, question: 'Quel est le vrai nom de Marilyn Monroe ?', answer: 'Norma Jeane Mortenson' },
  { theme: 'Cinéma', level: 8, question: 'Qui a réalisé le film 2001, l\'Odyssée de l\'espace ?', answer: 'Stanley Kubrick' },
  { theme: 'Cinéma', level: 8, question: 'Quel film d\'Hitchcock met en scène une attaque d\'oiseaux ?', answer: 'Les Oiseaux' },
  { theme: 'Cinéma', level: 9, question: 'Quel est le premier long-métrage d\'animation de Disney (1937) ?', answer: 'Blanche-Neige et les Sept Nains' },
  { theme: 'Cinéma', level: 9, question: 'Quel acteur a refusé l\'Oscar pour son rôle dans Le Parrain ?', answer: 'Marlon Brando' },
  { theme: 'Cinéma', level: 10, question: 'Quel film muet français a remporté l\'Oscar du meilleur film en 2012 ?', answer: 'The Artist' },
  { theme: 'Cinéma', level: 10, question: 'Qui est le réalisateur du film "Le Septième Sceau" ?', answer: 'Ingmar Bergman' },
  { theme: 'Musique', level: 1, question: 'De quel instrument joue un pianiste ?', answer: 'Piano' },
  { theme: 'Musique', level: 1, question: 'Qui chante "Libérée, délivrée" dans La Reine des Neiges ?', answer: 'Anaïs Delva' },
  { theme: 'Musique', level: 2, question: 'Quel groupe a chanté "Yellow Submarine" ?', answer: 'The Beatles' },
  { theme: 'Musique', level: 2, question: 'Qui est le "Roi de la Pop" ?', answer: 'Michael Jackson' },
  { theme: 'Musique', level: 3, question: 'Quel instrument a 6 cordes ?', answer: 'La guitare' },
  { theme: 'Musique', level: 3, question: 'Quelle chanteuse est célèbre pour "Rolling in the Deep" ?', answer: 'Adele' },
  { theme: 'Musique', level: 4, question: 'Quel groupe a chanté "Bohemian Rhapsody" ?', answer: 'Queen' },
  { theme: 'Musique', level: 4, question: 'Qui a composé "Les Quatre Saisons" ?', answer: 'Vivaldi' },
  { theme: 'Musique', level: 5, question: 'Quel rappeur s\'appelle en réalité Marshall Mathers ?', answer: 'Eminem' },
  { theme: 'Musique', level: 5, question: 'Dans quel pays est né le reggae ?', answer: 'Jamaïque' },
  { theme: 'Musique', level: 6, question: 'Qui a composé la "Lettre à Élise" ?', answer: 'Beethoven' },
  { theme: 'Musique', level: 6, question: 'Quel est le prénom de la chanteuse Lady Gaga ?', answer: 'Stefani' },
  { theme: 'Musique', level: 7, question: 'Quel groupe de rock a pour chanteur Mick Jagger ?', answer: 'The Rolling Stones' },
  { theme: 'Musique', level: 7, question: 'Qui a chanté "La Vie en rose" ?', answer: 'Édith Piaf' },
  { theme: 'Musique', level: 8, question: 'Quel artiste a sorti l\'album "Thriller" ?', answer: 'Michael Jackson' },
  { theme: 'Musique', level: 8, question: 'De quelle ville vient le groupe Nirvana ?', answer: 'Seattle' },
  { theme: 'Musique', level: 9, question: 'Quel compositeur autrichien est mort à 35 ans en 1791 ?', answer: 'Mozart' },
  { theme: 'Musique', level: 9, question: 'Qui est l\'interprète original de "Hallelujah" ?', answer: 'Leonard Cohen' },
  { theme: 'Musique', level: 10, question: 'Quel opéra de Wagner dure environ 15 heures au total ?', answer: 'L\'Anneau du Nibelung' },
  { theme: 'Musique', level: 10, question: 'Quel est le nom du chien dans la chanson "Qui a tué Grand\' Maman" de Polnareff ?', answer: 'Il n\'y a pas de chien' },
  { theme: 'Science', level: 1, question: 'Quelle planète est la plus proche du soleil ?', answer: 'Mercure' },
  { theme: 'Science', level: 1, question: 'À quelle température l\'eau bout-elle (en degrés Celsius) ?', answer: '100' },
  { theme: 'Science', level: 2, question: 'Quel gaz respirons-nous pour vivre ?', answer: 'Oxygène' },
  { theme: 'Science', level: 2, question: 'Combien de planètes y a-t-il dans notre système solaire ?', answer: '8' },
  { theme: 'Science', level: 3, question: 'Quel organe pompe le sang dans le corps humain ?', answer: 'Le cœur' },
  { theme: 'Science', level: 3, question: 'Quelle est la formule chimique de l\'eau ?', answer: 'H2O' },
  { theme: 'Science', level: 4, question: 'Quelle planète est surnommée la planète rouge ?', answer: 'Mars' },
  { theme: 'Science', level: 4, question: 'Quel est le plus grand mammifère marin ?', answer: 'La baleine bleue' },
  { theme: 'Science', level: 5, question: 'Qui a formulé la théorie de la relativité générale ?', answer: 'Albert Einstein' },
  { theme: 'Science', level: 5, question: 'Quel métal est liquide à température ambiante ?', answer: 'Le mercure' },
  { theme: 'Science', level: 6, question: 'Quelle est l\'unité de mesure de la résistance électrique ?', answer: 'L\'ohm' },
  { theme: 'Science', level: 6, question: 'Quel est le symbole chimique de l\'or ?', answer: 'Au' },
  { theme: 'Science', level: 7, question: 'Quelle partie de la cellule contient l\'ADN ?', answer: 'Le noyau' },
  { theme: 'Science', level: 7, question: 'Combien de paires de chromosomes possède un humain ?', answer: '23' },
  { theme: 'Science', level: 8, question: 'Qui a découvert la pénicilline ?', answer: 'Alexander Fleming' },
  { theme: 'Science', level: 8, question: 'Quelle est la vitesse de la lumière (en km/s, environ) ?', answer: '300000' },
  { theme: 'Science', level: 9, question: 'Quel est l\'élément le plus abondant dans l\'univers ?', answer: 'L\'hydrogène' },
  { theme: 'Science', level: 9, question: 'Quelle particule subatomique a une charge négative ?', answer: 'L\'électron' },
  { theme: 'Science', level: 10, question: 'Quel physicien a formulé le principe d\'incertitude ?', answer: 'Heisenberg' },
  { theme: 'Science', level: 10, question: 'Quelle est la période de demi-vie du Carbone 14 (environ) ?', answer: '5730 ans' },
  { theme: 'Animaux', level: 1, question: 'Quel animal aboie ?', answer: 'Le chien' },
  { theme: 'Animaux', level: 1, question: 'Quel animal a un long cou et des taches ?', answer: 'La girafe' },
  { theme: 'Animaux', level: 2, question: 'Quel animal est le roi de la jungle ?', answer: 'Le lion' },
  { theme: 'Animaux', level: 2, question: 'Quel oiseau ne peut pas voler et vit en Antarctique ?', answer: 'Le manchot' },
  { theme: 'Animaux', level: 3, question: 'Combien de pattes a une araignée ?', answer: '8' },
  { theme: 'Animaux', level: 3, question: 'Quel animal produit du lait pour faire de la mozzarella ?', answer: 'La bufflonne' },
  { theme: 'Animaux', level: 4, question: 'Quel est l\'animal terrestre le plus rapide ?', answer: 'Le guépard' },
  { theme: 'Animaux', level: 4, question: 'Quel marsupial saute et vit en Australie ?', answer: 'Le kangourou' },
  { theme: 'Animaux', level: 5, question: 'Quel est le plus gros animal terrestre ?', answer: 'L\'éléphant d\'Afrique' },
  { theme: 'Animaux', level: 5, question: 'Comment appelle-t-on le petit du cheval ?', answer: 'Le poulain' },
  { theme: 'Animaux', level: 6, question: 'Quel est le seul mammifère capable de voler ?', answer: 'La chauve-souris' },
  { theme: 'Animaux', level: 6, question: 'Quel animal a la morsure la plus puissante ?', answer: 'Le crocodile marin' },
  { theme: 'Animaux', level: 7, question: 'Quel oiseau est capable de voler à reculons ?', answer: 'Le colibri' },
  { theme: 'Animaux', level: 7, question: 'Combien de cœurs possède une pieuvre ?', answer: '3' },
  { theme: 'Animaux', level: 8, question: 'Quel est le nom scientifique de l\'homme ?', answer: 'Homo sapiens' },
  { theme: 'Animaux', level: 8, question: 'Quel mammifère pond des œufs ?', answer: 'L\'ornithorynque' },
  { theme: 'Animaux', level: 9, question: 'Quelle est la durée de gestation d\'un éléphant (en mois) ?', answer: '22' },
  { theme: 'Animaux', level: 9, question: 'Quel requin est le plus grand poisson du monde ?', answer: 'Le requin-baleine' },
  { theme: 'Animaux', level: 10, question: 'Quel animal marin possède la plus grande espérance de vie (plus de 400 ans) ?', answer: 'Le requin du Groenland' },
  { theme: 'Animaux', level: 10, question: 'Quel est l\'animal le plus venimeux du monde (une méduse) ?', answer: 'La cuboméduse' },
  { theme: 'Football', level: 1, question: 'Avec quelle partie du corps ne peut-on pas toucher le ballon au foot (sauf gardien) ?', answer: 'La main' },
  { theme: 'Football', level: 1, question: 'Quelle est la couleur du carton qui expulse un joueur ?', answer: 'Rouge' },
  { theme: 'Football', level: 2, question: 'Combien de joueurs y a-t-il dans une équipe de football sur le terrain ?', answer: '11' },
  { theme: 'Football', level: 2, question: 'Quel pays a gagné la Coupe du monde 2018 ?', answer: 'France' },
  { theme: 'Football', level: 3, question: 'Quel joueur est surnommé CR7 ?', answer: 'Cristiano Ronaldo' },
  { theme: 'Football', level: 3, question: 'Dans quel stade joue le PSG ?', answer: 'Le Parc des Princes' },
  { theme: 'Football', level: 4, question: 'Quel pays a remporté le plus de Coupes du monde ?', answer: 'Brésil' },
  { theme: 'Football', level: 4, question: 'Qui a marqué de la main contre l\'Angleterre en 1986 ?', answer: 'Diego Maradona' },
  { theme: 'Football', level: 5, question: 'Quel club français a gagné la Ligue des Champions en 1993 ?', answer: 'Olympique de Marseille' },
  { theme: 'Football', level: 5, question: 'Quel joueur a remporté 8 Ballons d\'Or ?', answer: 'Lionel Messi' },
  { theme: 'Football', level: 6, question: 'Qui est le meilleur buteur de l\'histoire de l\'équipe de France (en 2023) ?', answer: 'Olivier Giroud' },
  { theme: 'Football', level: 6, question: 'Dans quelle ville se trouve le stade Santiago Bernabéu ?', answer: 'Madrid' },
  { theme: 'Football', level: 7, question: 'Quel gardien soviétique était surnommé l\'Araignée Noire ?', answer: 'Lev Yachine' },
  { theme: 'Football', level: 7, question: 'En quelle année la France a-t-elle gagné sa première Coupe du monde ?', answer: '1998' },
  { theme: 'Football', level: 8, question: 'Quel club a remporté la Ligue des Champions 3 fois de suite (2016-2018) ?', answer: 'Real Madrid' },
  { theme: 'Football', level: 8, question: 'Qui a marqué le but de la victoire pour l\'Allemagne en finale 2014 ?', answer: 'Mario Götze' },
  { theme: 'Football', level: 9, question: 'Quel joueur a marqué 13 buts en une seule Coupe du monde (1958) ?', answer: 'Just Fontaine' },
  { theme: 'Football', level: 9, question: 'Quel est le seul club anglais invaincu sur une saison entière (2003-2004) ?', answer: 'Arsenal' },
  { theme: 'Football', level: 10, question: 'Quel pays a organisé la première Coupe du monde en 1930 ?', answer: 'Uruguay' },
  { theme: 'Football', level: 10, question: 'Qui est le meilleur buteur de l\'histoire de la Coupe du monde (16 buts) ?', answer: 'Miroslav Klose' },
  { theme: 'Jeux vidéo', level: 1, question: 'Quel est le métier de Mario ?', answer: 'Plombier' },
  { theme: 'Jeux vidéo', level: 1, question: 'Quel animal est Sonic ?', answer: 'Un hérisson' },
  { theme: 'Jeux vidéo', level: 2, question: 'Quel jeu consiste à empiler des briques de formes différentes ?', answer: 'Tetris' },
  { theme: 'Jeux vidéo', level: 2, question: 'Dans quel jeu attrape-t-on des monstres dans des boules ?', answer: 'Pokémon' },
  { theme: 'Jeux vidéo', level: 3, question: 'Quel est le prénom de la princesse que Mario doit sauver ?', answer: 'Peach' },
  { theme: 'Jeux vidéo', level: 3, question: 'Quel jeu de construction appartient à Microsoft (cubes) ?', answer: 'Minecraft' },
  { theme: 'Jeux vidéo', level: 4, question: 'Quel est le héros de la saga The Legend of Zelda ?', answer: 'Link' },
  { theme: 'Jeux vidéo', level: 4, question: 'Dans quel jeu incarne-t-on Lara Croft ?', answer: 'Tomb Raider' },
  { theme: 'Jeux vidéo', level: 5, question: 'Quel est le jeu le plus vendu de tous les temps (hors Tetris mobile) ?', answer: 'Minecraft' },
  { theme: 'Jeux vidéo', level: 5, question: 'Quelle entreprise a créé la PlayStation ?', answer: 'Sony' },
  { theme: 'Jeux vidéo', level: 6, question: 'Comment s\'appelle le frère de Mario ?', answer: 'Luigi' },
  { theme: 'Jeux vidéo', level: 6, question: 'Quel FPS se déroule durant la Seconde Guerre mondiale (début de la saga) ?', answer: 'Call of Duty' },
  { theme: 'Jeux vidéo', level: 7, question: 'Quel est le nom du monde dans World of Warcraft ?', answer: 'Azeroth' },
  { theme: 'Jeux vidéo', level: 7, question: 'Qui est le créateur de Metal Gear Solid ?', answer: 'Hideo Kojima' },
  { theme: 'Jeux vidéo', level: 8, question: 'Dans quelle année se déroule Cyberpunk ?', answer: '2077' },
  { theme: 'Jeux vidéo', level: 8, question: 'Quel est le nom du héros de Halo ?', answer: 'Master Chief' },
  { theme: 'Jeux vidéo', level: 9, question: 'Quelle console a précédé la Nintendo 64 ?', answer: 'Super Nintendo' },
  { theme: 'Jeux vidéo', level: 9, question: 'Quel est le premier jeu vidéo commercial (arcade) ?', answer: 'Computer Space' },
  { theme: 'Jeux vidéo', level: 10, question: 'Quel code célèbre est : Haut, Haut, Bas, Bas, Gauche, Droite, Gauche, Droite, B, A ?', answer: 'Le code Konami' },
  { theme: 'Jeux vidéo', level: 10, question: 'Quel personnage de jeu vidéo s\'appelait Jumpman à l\'origine ?', answer: 'Mario' },
  { theme: 'Littérature', level: 1, question: 'Qui a écrit Harry Potter ?', answer: 'J.K. Rowling' },
  { theme: 'Littérature', level: 1, question: 'Quel est le prénom de Roméo ?', answer: 'Roméo' },
  { theme: 'Littérature', level: 2, question: 'Quel célèbre détective habite au 221B Baker Street ?', answer: 'Sherlock Holmes' },
  { theme: 'Littérature', level: 2, question: 'Qui a écrit Les Misérables ?', answer: 'Victor Hugo' },
  { theme: 'Littérature', level: 3, question: 'Quel petit prince habite sur l\'astéroïde B 612 ?', answer: 'Le Petit Prince' },
  { theme: 'Littérature', level: 3, question: 'Qui a écrit Roméo et Juliette ?', answer: 'William Shakespeare' },
  { theme: 'Littérature', level: 4, question: 'Quel héros de BD est un reporter à la houpette ?', answer: 'Tintin' },
  { theme: 'Littérature', level: 4, question: 'Qui a écrit Le Tour du monde en 80 jours ?', answer: 'Jules Verne' },
  { theme: 'Littérature', level: 5, question: 'Quel livre sacré est utilisé par les chrétiens ?', answer: 'La Bible' },
  { theme: 'Littérature', level: 5, question: 'Qui a écrit L\'Étranger ?', answer: 'Albert Camus' },
  { theme: 'Littérature', level: 6, question: 'Quel est le titre du premier tome de À la recherche du temps perdu ?', answer: 'Du côté de chez Swann' },
  { theme: 'Littérature', level: 6, question: 'Qui a écrit 1984 ?', answer: 'George Orwell' },
  { theme: 'Littérature', level: 7, question: 'Quel auteur a créé le Comte de Monte-Cristo ?', answer: 'Alexandre Dumas' },
  { theme: 'Littérature', level: 7, question: 'Dans quel pays se déroule l\'action de Don Quichotte ?', answer: 'Espagne' },
  { theme: 'Littérature', level: 8, question: 'Qui a écrit Madame Bovary ?', answer: 'Gustave Flaubert' },
  { theme: 'Littérature', level: 8, question: 'Quel poète a écrit Les Fleurs du mal ?', answer: 'Charles Baudelaire' },
  { theme: 'Littérature', level: 9, question: 'Qui a reçu le prix Nobel de littérature en 1964 et l\'a refusé ?', answer: 'Jean-Paul Sartre' },
  { theme: 'Littérature', level: 9, question: 'Quel est le vrai nom de Molière ?', answer: 'Jean-Baptiste Poquelin' },
  { theme: 'Littérature', level: 10, question: 'Qui a écrit Ulysse (roman de 1922) ?', answer: 'James Joyce' },
  { theme: 'Littérature', level: 10, question: 'Quel auteur russe a écrit Guerre et Paix ?', answer: 'Léon Tolstoï' },
  { theme: 'Cuisine', level: 1, question: 'Quel est l\'ingrédient principal de l\'omelette ?', answer: 'L\'œuf' },
  { theme: 'Cuisine', level: 1, question: 'Quelle est la couleur d\'une banane mûre ?', answer: 'Jaune' },
  { theme: 'Cuisine', level: 2, question: 'De quel pays vient la pizza ?', answer: 'Italie' },
  { theme: 'Cuisine', level: 2, question: 'Quel légume fait pleurer quand on l\'épluche ?', answer: 'L\'oignon' },
  { theme: 'Cuisine', level: 3, question: 'Avec quoi fait-on du vin ?', answer: 'Du raisin' },
  { theme: 'Cuisine', level: 3, question: 'Quel est l\'ingrédient principal du guacamole ?', answer: 'L\'avocat' },
  { theme: 'Cuisine', level: 4, question: 'Quel pays est célèbre pour ses sushis ?', answer: 'Japon' },
  { theme: 'Cuisine', level: 4, question: 'Quelle pâtisserie est faite de pâte à choux et de forme allongée ?', answer: 'L\'éclair' },
  { theme: 'Cuisine', level: 5, question: 'Quel est l\'ingrédient de base du houmous ?', answer: 'Le pois chiche' },
  { theme: 'Cuisine', level: 5, question: 'Quelle épice est la plus chère du monde ?', answer: 'Le safran' },
  { theme: 'Cuisine', level: 6, question: 'De quelle région vient le cassoulet ?', answer: 'Languedoc' },
  { theme: 'Cuisine', level: 6, question: 'Quelle est la viande utilisée dans un bœuf bourguignon ?', answer: 'Le bœuf' },
  { theme: 'Cuisine', level: 7, question: 'Quel champignon est recherché par les cochons ou les chiens ?', answer: 'La truffe' },
  { theme: 'Cuisine', level: 7, question: 'Quel est l\'alcool principal du Mojito ?', answer: 'Le rhum' },
  { theme: 'Cuisine', level: 8, question: 'Quel est le nom du beurre clarifié utilisé dans la cuisine indienne ?', answer: 'Ghee' },
  { theme: 'Cuisine', level: 8, question: 'Quelle est la différence entre un macaron et un macaron de Nancy ?', answer: 'La crème' },
  { theme: 'Cuisine', level: 9, question: 'De quel poisson proviennent les œufs de caviar ?', answer: 'L\'esturgeon' },
  { theme: 'Cuisine', level: 9, question: 'Quel chef français a été nommé "Cuisinier du siècle" en 1989 ?', answer: 'Paul Bocuse' },
  { theme: 'Cuisine', level: 10, question: 'Quelle bactérie est responsable de la fermentation du vinaigre ?', answer: 'L\'acétobacter' },
  { theme: 'Cuisine', level: 10, question: 'Quel est le nom japonais du poisson-globe toxique ?', answer: 'Fugu' },
  { theme: 'Séries', level: 1, question: 'Quelle couleur est le canapé des Simpson ?', answer: 'Marron' },
  { theme: 'Séries', level: 1, question: 'Comment s\'appelle l\'ami de Joey dans Friends ?', answer: 'Chandler' },
  { theme: 'Séries', level: 2, question: 'Quelle série se déroule à Westeros ?', answer: 'Game of Thrones' },
  { theme: 'Séries', level: 2, question: 'Qui est le professeur de chimie dans Breaking Bad ?', answer: 'Walter White' },
  { theme: 'Séries', level: 3, question: 'Dans quelle ville se déroule Stranger Things ?', answer: 'Hawkins' },
  { theme: 'Séries', level: 3, question: 'Quelle série met en scène des braqueurs avec des masques de Dali ?', answer: 'La Casa de Papel' },
  { theme: 'Séries', level: 4, question: 'Quel est le prénom de Dr House ?', answer: 'Gregory' },
  { theme: 'Séries', level: 4, question: 'Quelle série suit la famille Shelby ?', answer: 'Peaky Blinders' },
  { theme: 'Séries', level: 5, question: 'Qui joue le rôle principal dans The Witcher ?', answer: 'Henry Cavill' },
  { theme: 'Séries', level: 5, question: 'Dans quelle série trouve-t-on l\'île "Dharma" ?', answer: 'Lost' },
  { theme: 'Séries', level: 6, question: 'Quelle série animée se déroule en l\'an 3000 ?', answer: 'Futurama' },
  { theme: 'Séries', level: 6, question: 'Qui a créé la série Black Mirror ?', answer: 'Charlie Brooker' },
  { theme: 'Séries', level: 7, question: 'Quel est le nom de l\'hôpital dans Grey\'s Anatomy ?', answer: 'Grey Sloan Memorial' },
  { theme: 'Séries', level: 7, question: 'Dans quelle série entend-on "Winter is coming" ?', answer: 'Game of Thrones' },
  { theme: 'Séries', level: 8, question: 'Quelle série a pour héros Don Draper ?', answer: 'Mad Men' },
  { theme: 'Séries', level: 8, question: 'Quel est le spin-off de Breaking Bad centré sur l\'avocat ?', answer: 'Better Call Saul' },
  { theme: 'Séries', level: 9, question: 'Quelle est la série la plus longue de l\'histoire (soap opera) ?', answer: 'Haine et Passion' },
  { theme: 'Séries', level: 9, question: 'Qui a tué Laura Palmer dans Twin Peaks ?', answer: 'Son père' },
  { theme: 'Séries', level: 10, question: 'Dans quelle série de HBO suit-on la famille Roy ?', answer: 'Succession' },
  { theme: 'Séries', level: 10, question: 'Quel est le numéro de l\'appartement de Jerry dans Seinfeld ?', answer: '5A' },
  { theme: 'Corps humain', level: 1, question: 'Combien avons-nous de doigts sur une main ?', answer: '5' },
  { theme: 'Corps humain', level: 1, question: 'Où se trouvent les dents ?', answer: 'Dans la bouche' },
  { theme: 'Corps humain', level: 2, question: 'Quel est le plus grand organe du corps humain ?', answer: 'La peau' },
  { theme: 'Corps humain', level: 2, question: 'Combien d\'yeux a un humain normalement ?', answer: '2' },
  { theme: 'Corps humain', level: 3, question: 'Quel est l\'os le plus long du corps ?', answer: 'Le fémur' },
  { theme: 'Corps humain', level: 3, question: 'Quel organe filtre l\'urine ?', answer: 'Les reins' },
  { theme: 'Corps humain', level: 4, question: 'Combien d\'os y a-t-il dans le corps humain adulte ?', answer: '206' },
  { theme: 'Corps humain', level: 4, question: 'Quel est le groupe sanguin universel (donneur) ?', answer: 'O négatif' },
  { theme: 'Corps humain', level: 5, question: 'Quelle protéine transporte l\'oxygène dans le sang ?', answer: 'L\'hémoglobine' },
  { theme: 'Corps humain', level: 5, question: 'Comment s\'appelle le trou au centre de l\'iris ?', answer: 'La pupille' },
  { theme: 'Corps humain', level: 6, question: 'Quel est l\'os le plus petit du corps humain ?', answer: 'L\'étrier' },
  { theme: 'Corps humain', level: 6, question: 'Combien de lobes possède le poumon droit ?', answer: '3' },
  { theme: 'Corps humain', level: 7, question: 'Quelle glande produit l\'insuline ?', answer: 'Le pancréas' },
  { theme: 'Corps humain', level: 7, question: 'Quelle vitamine est produite grâce au soleil ?', answer: 'Vitamine D' },
  { theme: 'Corps humain', level: 8, question: 'Quel est le muscle le plus fort du corps par rapport à sa taille ?', answer: 'Le masséter' },
  { theme: 'Corps humain', level: 8, question: 'Combien de paires de côtes a un être humain ?', answer: '12' },
  { theme: 'Corps humain', level: 9, question: 'Quelle partie du cerveau gère l\'équilibre ?', answer: 'Le cervelet' },
  { theme: 'Corps humain', level: 9, question: 'Quel est le nom de la première vertèbre cervicale ?', answer: 'Atlas' },
  { theme: 'Corps humain', level: 10, question: 'Combien de muscles sont nécessaires pour sourire ?', answer: '17' },
  { theme: 'Corps humain', level: 10, question: 'Quel pourcentage d\'eau contient le corps humain adulte (environ) ?', answer: '60%' },
  { theme: 'Mythologie', level: 1, question: 'Qui est le dieu de la foudre dans la mythologie grecque ?', answer: 'Zeus' },
  { theme: 'Mythologie', level: 1, question: 'Quel dieu a un marteau dans la mythologie nordique ?', answer: 'Thor' },
  { theme: 'Mythologie', level: 2, question: 'Qui est le dieu des mers grec ?', answer: 'Poséidon' },
  { theme: 'Mythologie', level: 2, question: 'Qui est la déesse de l\'amour grecque ?', answer: 'Aphrodite' },
  { theme: 'Mythologie', level: 3, question: 'Quel héros a réalisé 12 travaux ?', answer: 'Hercule' },
  { theme: 'Mythologie', level: 3, question: 'Qui a volé le feu aux dieux ?', answer: 'Prométhée' },
  { theme: 'Mythologie', level: 4, question: 'Qui est le dieu des enfers grec ?', answer: 'Hadès' },
  { theme: 'Mythologie', level: 4, question: 'Quel animal est Pégase ?', answer: 'Un cheval ailé' },
  { theme: 'Mythologie', level: 5, question: 'Qui est le père de Thor ?', answer: 'Odin' },
  { theme: 'Mythologie', level: 5, question: 'Quel héros a tué le Minotaure ?', answer: 'Thésée' },
  { theme: 'Mythologie', level: 6, question: 'Qui est le dieu romain de la guerre ?', answer: 'Mars' },
  { theme: 'Mythologie', level: 6, question: 'Quelle créature a des serpents à la place des cheveux ?', answer: 'Méduse' },
  { theme: 'Mythologie', level: 7, question: 'Qui est le messager des dieux grecs ?', answer: 'Hermès' },
  { theme: 'Mythologie', level: 7, question: 'Quel dieu égyptien a une tête de chacal ?', answer: 'Anubis' },
  { theme: 'Mythologie', level: 8, question: 'Comment s\'appelle le paradis des guerriers vikings ?', answer: 'Valhalla' },
  { theme: 'Mythologie', level: 8, question: 'Qui est la femme de Zeus ?', answer: 'Héra' },
  { theme: 'Mythologie', level: 9, question: 'Quel fleuve sépare le monde des vivants et des morts ?', answer: 'Le Styx' },
  { theme: 'Mythologie', level: 9, question: 'Qui est le dieu du soleil égyptien ?', answer: 'Râ' },
  { theme: 'Mythologie', level: 10, question: 'Quel géant porte la voûte céleste sur ses épaules ?', answer: 'Atlas' },
  { theme: 'Mythologie', level: 10, question: 'Quel est le nom du loup géant dans la mythologie nordique ?', answer: 'Fenrir' },
  { theme: 'Technologie', level: 1, question: 'Avec quoi tape-t-on sur un ordinateur ?', answer: 'Un clavier' },
  { theme: 'Technologie', level: 1, question: 'Que signifie "PC" ?', answer: 'Personal Computer' },
  { theme: 'Technologie', level: 2, question: 'Quelle entreprise a créé l\'iPhone ?', answer: 'Apple' },
  { theme: 'Technologie', level: 2, question: 'Quel réseau social a un logo bleu avec un "f" ?', answer: 'Facebook' },
  { theme: 'Technologie', level: 3, question: 'Qui a fondé Microsoft ?', answer: 'Bill Gates' },
  { theme: 'Technologie', level: 3, question: 'Que signifie "www" ?', answer: 'World Wide Web' },
  { theme: 'Technologie', level: 4, question: 'Quel est le moteur de recherche le plus utilisé ?', answer: 'Google' },
  { theme: 'Technologie', level: 4, question: 'En quelle année a été lancé le premier iPhone ?', answer: '2007' },
  { theme: 'Technologie', level: 5, question: 'Qui est le fondateur de Facebook ?', answer: 'Mark Zuckerberg' },
  { theme: 'Technologie', level: 5, question: 'Quel langage de programmation est utilisé pour le web (côté client) ?', answer: 'JavaScript' },
  { theme: 'Technologie', level: 6, question: 'Que signifie "USB" ?', answer: 'Universal Serial Bus' },
  { theme: 'Technologie', level: 6, question: 'Quel entrepreneur a fondé SpaceX ?', answer: 'Elon Musk' },
  { theme: 'Technologie', level: 7, question: 'Quel est le système d\'exploitation mobile de Google ?', answer: 'Android' },
  { theme: 'Technologie', level: 7, question: 'Que signifie "Wi-Fi" (abus de langage courant) ?', answer: 'Wireless Fidelity' },
  { theme: 'Technologie', level: 8, question: 'En quelle année est né Internet (ARPANET) ?', answer: '1969' },
  { theme: 'Technologie', level: 8, question: 'Qui est considéré comme le père de l\'informatique ?', answer: 'Alan Turing' },
  { theme: 'Technologie', level: 9, question: 'Quel est le nom du premier ordinateur électronique ?', answer: 'ENIAC' },
  { theme: 'Technologie', level: 9, question: 'Quelle entreprise a créé le langage Java ?', answer: 'Sun Microsystems' },
  { theme: 'Technologie', level: 10, question: 'Quel métal rare est indispensable aux smartphones ?', answer: 'Le coltan' },
  { theme: 'Technologie', level: 10, question: 'Qui a inventé le World Wide Web ?', answer: 'Tim Berners-Lee' },
  { theme: 'BD', level: 1, question: 'Quelle couleur est la peau des Schtroumpfs ?', answer: 'Bleue' },
  { theme: 'BD', level: 1, question: 'Quel animal est Garfield ?', answer: 'Un chat' },
  { theme: 'BD', level: 2, question: 'Quel Gaulois est tombé dans la marmite quand il était petit ?', answer: 'Obélix' },
  { theme: 'BD', level: 2, question: 'Qui est le père de Titeuf ?', answer: 'Zep' },
  { theme: 'BD', level: 3, question: 'Quel héros tire plus vite que son ombre ?', answer: 'Lucky Luke' },
  { theme: 'BD', level: 3, question: 'Quel est le métier de Gaston Lagaffe ?', answer: 'Employé de bureau' },
  { theme: 'BD', level: 4, question: 'Dans quelle ville habite Batman ?', answer: 'Gotham City' },
  { theme: 'BD', level: 4, question: 'Qui est le capitaine alcoolique ami de Tintin ?', answer: 'Capitaine Haddock' },
  { theme: 'BD', level: 5, question: 'Quel est le vrai nom de Spider-Man ?', answer: 'Peter Parker' },
  { theme: 'BD', level: 5, question: 'Qui a créé Astérix ?', answer: 'Goscinny et Uderzo' },
  { theme: 'BD', level: 6, question: 'Quel est le chien de Lucky Luke ?', answer: 'Rantanplan' },
  { theme: 'BD', level: 6, question: 'Dans quel journal est né Spirou ?', answer: 'Le Journal de Spirou' },
  { theme: 'BD', level: 7, question: 'Quel est le prénom de la Castafiore ?', answer: 'Bianca' },
  { theme: 'BD', level: 7, question: 'Qui est l\'ennemi juré des Schtroumpfs ?', answer: 'Gargamel' },
  { theme: 'BD', level: 8, question: 'Quel est le vrai nom de Superman ?', answer: 'Kal-El' },
  { theme: 'BD', level: 8, question: 'Qui a dessiné Corto Maltese ?', answer: 'Hugo Pratt' },
  { theme: 'BD', level: 9, question: 'Quel héros de BD a été créé par Hergé ?', answer: 'Tintin' },
  { theme: 'BD', level: 9, question: 'Dans quelle ville fictive vit Superman ?', answer: 'Metropolis' },
  { theme: 'BD', level: 10, question: 'Quel est le tout premier album de Tintin ?', answer: 'Tintin au pays des Soviets' },
  { theme: 'BD', level: 10, question: 'Quel est le nom du chat de Gargamel ?', answer: 'Azraël' },
  { theme: 'Nature', level: 1, question: 'Quelle est la couleur de l\'herbe ?', answer: 'Verte' },
  { theme: 'Nature', level: 1, question: 'Qu\'est-ce qui tombe des nuages ?', answer: 'La pluie' },
  { theme: 'Nature', level: 2, question: 'Quelle saison vient après l\'été ?', answer: 'L\'automne' },
  { theme: 'Nature', level: 2, question: 'De quoi se nourrissent les abeilles ?', answer: 'De nectar' },
  { theme: 'Nature', level: 3, question: 'Quel arbre produit des glands ?', answer: 'Le chêne' },
  { theme: 'Nature', level: 3, question: 'Quel phénomène naturel est un arc coloré ?', answer: 'Arc-en-ciel' },
  { theme: 'Nature', level: 4, question: 'Quel gaz les arbres absorbent-ils ?', answer: 'CO2' },
  { theme: 'Nature', level: 4, question: 'Quelle est la plus haute montagne du monde ?', answer: 'Everest' },
  { theme: 'Nature', level: 5, question: 'Quel est le plus grand désert chaud du monde ?', answer: 'Le Sahara' },
  { theme: 'Nature', level: 5, question: 'Quel est l\'arbre emblématique du Canada ?', answer: 'L\'érable' },
  { theme: 'Nature', level: 6, question: 'Quel est le nom du processus par lequel les plantes créent de l\'énergie ?', answer: 'La photosynthèse' },
  { theme: 'Nature', level: 6, question: 'Quel océan borde la côte ouest de la France ?', answer: 'L\'océan Atlantique' },
  { theme: 'Nature', level: 7, question: 'Quelle est la couche de gaz qui protège la Terre des UV ?', answer: 'La couche d\'ozone' },
  { theme: 'Nature', level: 7, question: 'Quel est le fleuve le plus long du monde (débat avec le Nil) ?', answer: 'L\'Amazone' },
  { theme: 'Nature', level: 8, question: 'Quel est le nom du supercontinent unique d\'il y a 250 millions d\'années ?', answer: 'La Pangée' },
  { theme: 'Nature', level: 8, question: 'Quel est l\'arbre le plus grand du monde (espèce) ?', answer: 'Séquoia' },
  { theme: 'Nature', level: 9, question: 'Quelle est la fosse marine la plus profonde ?', answer: 'La fosse des Mariannes' },
  { theme: 'Nature', level: 9, question: 'Quel volcan italien a détruit Pompéi ?', answer: 'Le Vésuve' },
  { theme: 'Nature', level: 10, question: 'Quel est le nom du nuage d\'orage par excellence ?', answer: 'Cumulonimbus' },
  { theme: 'Nature', level: 10, question: 'Quel est l\'âge estimé de la Terre ?', answer: '4,5 milliards d\'années' },
  { theme: 'Astronomie', level: 1, question: 'Qu\'est-ce qui brille dans le ciel la nuit ?', answer: 'La Lune' },
  { theme: 'Astronomie', level: 1, question: 'Le Soleil est-il une planète ou une étoile ?', answer: 'Une étoile' },
  { theme: 'Astronomie', level: 2, question: 'Sur quelle planète vivons-nous ?', answer: 'Terre' },
  { theme: 'Astronomie', level: 2, question: 'Quelle planète a des anneaux visibles ?', answer: 'Saturne' },
  { theme: 'Astronomie', level: 3, question: 'Quelle est la plus grosse planète du système solaire ?', answer: 'Jupiter' },
  { theme: 'Astronomie', level: 3, question: 'Combien de temps met la Terre pour faire le tour du Soleil ?', answer: '365 jours' },
  { theme: 'Astronomie', level: 4, question: 'Quelle est la galaxie dans laquelle nous vivons ?', answer: 'La Voie lactée' },
  { theme: 'Astronomie', level: 4, question: 'Quel est le satellite naturel de la Terre ?', answer: 'La Lune' },
  { theme: 'Astronomie', level: 5, question: 'Quelle planète n\'est plus considérée comme une planète depuis 2006 ?', answer: 'Pluton' },
  { theme: 'Astronomie', level: 5, question: 'Quelle est l\'étoile la plus proche de la Terre ?', answer: 'Le Soleil' },
  { theme: 'Astronomie', level: 6, question: 'Comment appelle-t-on une explosion d\'étoile ?', answer: 'Supernova' },
  { theme: 'Astronomie', level: 6, question: 'Quelle est la deuxième planète du système solaire ?', answer: 'Vénus' },
  { theme: 'Astronomie', level: 7, question: 'Qui a dit "Et pourtant elle tourne" ?', answer: 'Galilée' },
  { theme: 'Astronomie', level: 7, question: 'Quelle est la distance Terre-Soleil (en UA) ?', answer: '1' },
  { theme: 'Astronomie', level: 8, question: 'Quelle est l\'étoile la plus proche du Soleil ?', answer: 'Proxima du Centaure' },
  { theme: 'Astronomie', level: 8, question: 'Qu\'est-ce qu\'un trou noir ?', answer: 'Un objet céleste très dense' },
  { theme: 'Astronomie', level: 9, question: 'Quel est le nom de notre galaxie voisine la plus proche ?', answer: 'Andromède' },
  { theme: 'Astronomie', level: 9, question: 'Quelle est la température à la surface du Soleil (environ) ?', answer: '5500°C' },
  { theme: 'Astronomie', level: 10, question: 'Quel objet céleste est classé 1 Ceres ?', answer: 'Une planète naine' },
  { theme: 'Astronomie', level: 10, question: 'Quelle sonde spatiale a quitté le système solaire ?', answer: 'Voyager 1' },
  { theme: 'Art', level: 1, question: 'Quelle est la couleur principale des Tournesols de Van Gogh ?', answer: 'Jaune' },
  { theme: 'Art', level: 1, question: 'Quel objet manque à la Vénus de Milo ?', answer: 'Les bras' },
  { theme: 'Art', level: 2, question: 'Dans quel musée se trouve La Joconde ?', answer: 'Le Louvre' },
  { theme: 'Art', level: 2, question: 'Quel peintre a coupé son oreille ?', answer: 'Vincent van Gogh' },
  { theme: 'Art', level: 3, question: 'Qui a peint le plafond de la chapelle Sixtine ?', answer: 'Michel-Ange' },
  { theme: 'Art', level: 3, question: 'Quel peintre espagnol est le maître du cubisme ?', answer: 'Pablo Picasso' },
  { theme: 'Art', level: 4, question: 'Quel artiste est célèbre pour ses boîtes de soupe Campbell ?', answer: 'Andy Warhol' },
  { theme: 'Art', level: 4, question: 'Quelle ville est associée à l\'artiste Banksy ?', answer: 'Bristol' },
  { theme: 'Art', level: 5, question: 'Qui a peint "Le Cri" ?', answer: 'Edvard Munch' },
  { theme: 'Art', level: 5, question: 'Quel mouvement artistique est associé à Claude Monet ?', answer: 'Impressionnisme' },
  { theme: 'Art', level: 6, question: 'Qui a sculpté "Le Penseur" ?', answer: 'Auguste Rodin' },
  { theme: 'Art', level: 6, question: 'Quel peintre mexicain était célèbre pour ses monosourcils ?', answer: 'Frida Kahlo' },
  { theme: 'Art', level: 7, question: 'Qui a peint "La Jeune Fille à la perle" ?', answer: 'Johannes Vermeer' },
  { theme: 'Art', level: 7, question: 'Quel artiste est connu pour ses montres molles ?', answer: 'Salvador Dalí' },
  { theme: 'Art', level: 8, question: 'Quel est le prénom du peintre Douanier Rousseau ?', answer: 'Henri' },
  { theme: 'Art', level: 8, question: 'Qui a peint "La Liberté guidant le peuple" ?', answer: 'Eugène Delacroix' },
  { theme: 'Art', level: 9, question: 'Quel peintre est l\'auteur du tableau "Guernica" ?', answer: 'Pablo Picasso' },
  { theme: 'Art', level: 9, question: 'Qui a peint "Les Époux Arnolfini" (détail du miroir célèbre) ?', answer: 'Jan van Eyck' },
  { theme: 'Art', level: 10, question: 'Quel artiste a réalisé l\'œuvre "Fontaine" (un urinoir renversé) en 1917 ?', answer: 'Marcel Duchamp' },
  { theme: 'Art', level: 10, question: 'Qui a peint "Le Radeau de la Méduse" ?', answer: 'Théodore Géricault' },

  { theme: 'Mathématiques', level: 1, question: 'Combien font 2 + 2 ?', answer: '4' },
  { theme: 'Mathématiques', level: 1, question: 'Quelle est la forme d\'un ballon de foot classique (en 2D) ?', answer: 'Un cercle' },
  { theme: 'Mathématiques', level: 2, question: 'Combien de côtés a un triangle ?', answer: '3' },
  { theme: 'Mathématiques', level: 2, question: 'Quel est le résultat de 10 fois 10 ?', answer: '100' },
  { theme: 'Mathématiques', level: 3, question: 'Quel chiffre romain représente 5 ?', answer: 'V' },
  { theme: 'Mathématiques', level: 3, question: 'Comment appelle-t-on un angle de 90 degrés ?', answer: 'Angle droit' },
  { theme: 'Mathématiques', level: 4, question: 'Quel est le carré de 9 ?', answer: '81' },
  { theme: 'Mathématiques', level: 4, question: 'Combien de secondes y a-t-il dans une minute ?', answer: '60' },
  { theme: 'Mathématiques', level: 5, question: 'Quelle est la valeur approchée de Pi (2 décimales) ?', answer: '3,14' },
  { theme: 'Mathématiques', level: 5, question: 'Comment appelle-t-on un triangle avec 3 côtés égaux ?', answer: 'Équilatéral' },
  { theme: 'Mathématiques', level: 6, question: 'Quel est le nom du côté le plus long d\'un triangle rectangle ?', answer: 'L\'hypoténuse' },
  { theme: 'Mathématiques', level: 6, question: 'Combien font 12 au carré ?', answer: '144' },
  { theme: 'Mathématiques', level: 7, question: 'Quel est le périmètre d\'un cercle de diamètre D ?', answer: 'Pi fois D' },
  { theme: 'Mathématiques', level: 7, question: 'Quel mathématicien a un théorème sur les triangles rectangles ?', answer: 'Pythagore' },
  { theme: 'Mathématiques', level: 8, question: 'Quelle est la racine carrée de 225 ?', answer: '15' },
  { theme: 'Mathématiques', level: 8, question: 'Qui est considéré comme le "prince des mathématiciens" ?', answer: 'Carl Friedrich Gauss' },
  { theme: 'Mathématiques', level: 9, question: 'Quelle lettre grecque représente la somme en maths ?', answer: 'Sigma' },
  { theme: 'Mathématiques', level: 9, question: 'Quel est le nombre d\'or (à 1 décimale près) ?', answer: '1,6' },
  { theme: 'Mathématiques', level: 10, question: 'Quelle conjecture célèbre a été démontrée par Andrew Wiles en 1994 ?', answer: 'Le dernier théorème de Fermat' },
  { theme: 'Mathématiques', level: 10, question: 'Quel nombre est la base du logarithme népérien (e) ?', answer: '2,718' },

  { theme: 'Marvel/DC', level: 1, question: 'Quelle est la couleur de Hulk ?', answer: 'Vert' },
  { theme: 'Marvel/DC', level: 1, question: 'Quel héros porte un bouclier avec une étoile ?', answer: 'Captain America' },
  { theme: 'Marvel/DC', level: 2, question: 'Quel animal représente Batman ?', answer: 'La chauve-souris' },
  { theme: 'Marvel/DC', level: 2, question: 'De quelle planète vient Superman ?', answer: 'Krypton' },
  { theme: 'Marvel/DC', level: 3, question: 'Quel est le vrai nom d\'Iron Man ?', answer: 'Tony Stark' },
  { theme: 'Marvel/DC', level: 3, question: 'Qui est la cousine de Superman ?', answer: 'Supergirl' },
  { theme: 'Marvel/DC', level: 4, question: 'Quel est le métal du squelette de Wolverine ?', answer: 'Adamantium' },
  { theme: 'Marvel/DC', level: 4, question: 'Dans quelle ville fictive Batman combat-il le crime ?', answer: 'Gotham City' },
  { theme: 'Marvel/DC', level: 5, question: 'Qui est le frère adoptif et ennemi de Thor ?', answer: 'Loki' },
  { theme: 'Marvel/DC', level: 5, question: 'Quel groupe de héros inclut Mr Fantastique et la Chose ?', answer: 'Les 4 Fantastiques' },
  { theme: 'Marvel/DC', level: 6, question: 'Quel est le nom du majordome de Batman ?', answer: 'Alfred' },
  { theme: 'Marvel/DC', level: 6, question: 'Quelle pierre verte affaiblit Superman ?', answer: 'La kryptonite' },
  { theme: 'Marvel/DC', level: 7, question: 'Quel grand méchant claque des doigts dans Infinity War ?', answer: 'Thanos' },
  { theme: 'Marvel/DC', level: 7, question: 'Quel est le vrai nom de Wonder Woman (chez les Amazones) ?', answer: 'Diana' },
  { theme: 'Marvel/DC', level: 8, question: 'Qui a créé la plupart des héros Marvel avec Jack Kirby ?', answer: 'Stan Lee' },
  { theme: 'Marvel/DC', level: 8, question: 'Quel est le nom de l\'équipe de super-vilains de DC (Harley Quinn, Deadshot...) ?', answer: 'Suicide Squad' },
  { theme: 'Marvel/DC', level: 9, question: 'Quel héros est l\'avocat aveugle Matt Murdock ?', answer: 'Daredevil' },
  { theme: 'Marvel/DC', level: 9, question: 'Quel est le nom du symbiote noir ennemi de Spider-Man ?', answer: 'Venom' },
  { theme: 'Marvel/DC', level: 10, question: 'Quel est le tout premier super-héros créé (Action Comics #1) ?', answer: 'Superman' },
  { theme: 'Marvel/DC', level: 10, question: 'Quel personnage Marvel brise le quatrième mur ?', answer: 'Deadpool' },

  { theme: 'Sport', level: 1, question: 'Avec quoi joue-t-on au tennis ?', answer: 'Une raquette' },
  { theme: 'Sport', level: 1, question: 'Sur quelle surface patine-t-on ?', answer: 'La glace' },
  { theme: 'Sport', level: 2, question: 'Quel sport se joue avec un ballon ovale ?', answer: 'Le rugby' },
  { theme: 'Sport', level: 2, question: 'Combien y a-t-il d\'anneaux sur le drapeau olympique ?', answer: '5' },
  { theme: 'Sport', level: 3, question: 'Dans quel sport utilise-t-on un volant ?', answer: 'Le badminton' },
  { theme: 'Sport', level: 3, question: 'Quelle course cycliste fait le tour de la France en juillet ?', answer: 'Le Tour de France' },
  { theme: 'Sport', level: 4, question: 'Combien de points vaut un panier de basket classique ?', answer: '2' },
  { theme: 'Sport', level: 4, question: 'Quel art martial japonais signifie "la voie de la souplesse" ?', answer: 'Judo' },
  { theme: 'Sport', level: 5, question: 'Quelle est la distance d\'un marathon (en km) ?', answer: '42,195' },
  { theme: 'Sport', level: 5, question: 'Quel joueur de tennis espagnol est le roi de la terre battue ?', answer: 'Rafael Nadal' },
  { theme: 'Sport', level: 6, question: 'Combien de joueurs y a-t-il dans une équipe de handball ?', answer: '7' },
  { theme: 'Sport', level: 6, question: 'Dans quel sport le terme "Ace" est-il utilisé ?', answer: 'Tennis' },
  { theme: 'Sport', level: 7, question: 'Quel pays a inventé le rugby ?', answer: 'Angleterre' },
  { theme: 'Sport', level: 7, question: 'Qui détient le record du monde du 100m (en 2023) ?', answer: 'Usain Bolt' },
  { theme: 'Sport', level: 8, question: 'Quel sport pratique-t-on dans un vélodrome ?', answer: 'Cyclisme sur piste' },
  { theme: 'Sport', level: 8, question: 'En quelle année ont eu lieu les premiers JO modernes à Athènes ?', answer: '1896' },
  { theme: 'Sport', level: 9, question: 'Quel est le seul Grand Chelem de tennis joué sur gazon ?', answer: 'Wimbledon' },
  { theme: 'Sport', level: 9, question: 'Quel boxeur a dit "Vole comme un papillon, pique comme une abeille" ?', answer: 'Muhammad Ali' },
  { theme: 'Sport', level: 10, question: 'Quelle ville a accueilli les Jeux Olympiques d\'hiver de 1968 ?', answer: 'Grenoble' },
  { theme: 'Sport', level: 10, question: 'Quel est le score maximal possible dans une partie de bowling ?', answer: '300' },

  { theme: 'Langue française', level: 1, question: 'Quelle est la première lettre de l\'alphabet ?', answer: 'A' },
  { theme: 'Langue française', level: 1, question: 'Quel est le contraire de "grand" ?', answer: 'Petit' },
  { theme: 'Langue française', level: 2, question: 'Combien y a-t-il de voyelles en français (y compris le Y) ?', answer: '6' },
  { theme: 'Langue française', level: 2, question: 'Quel signe de ponctuation termine une question ?', answer: 'Point d\'interrogation' },
  { theme: 'Langue française', level: 3, question: 'Comment appelle-t-on un mot qui a le même sens qu\'un autre ?', answer: 'Synonyme' },
  { theme: 'Langue française', level: 3, question: 'Quel est le pluriel de "cheval" ?', answer: 'Chevaux' },
  { theme: 'Langue française', level: 4, question: 'Quel est l\'infinitif du verbe "nous sommes" ?', answer: 'Être' },
  { theme: 'Langue française', level: 4, question: 'Comment appelle-t-on un mot qui se lit dans les deux sens (ex: Laval) ?', answer: 'Palindrome' },
  { theme: 'Langue française', level: 5, question: 'Quel accent trouve-t-on sur le "u" de "où" (lieu) ?', answer: 'Grave' },
  { theme: 'Langue française', level: 5, question: 'Quel est le féminin de "bouc" ?', answer: 'Chèvre' },
  { theme: 'Langue française', level: 6, question: 'Comment écrit-on "70" en lettres en Belgique ?', answer: 'Septante' },
  { theme: 'Langue française', level: 6, question: 'Quel est le pluriel de "chou-fleur" ?', answer: 'Choux-fleurs' },
  { theme: 'Langue française', level: 7, question: 'Que signifie le préfixe "poly" ?', answer: 'Plusieurs' },
  { theme: 'Langue française', level: 7, question: 'Quelle figure de style consiste à dire "c\'est un roc, c\'est un pic" ?', answer: 'L\'accumulation' },
  { theme: 'Langue française', level: 8, question: 'De quelle langue vient le mot "parking" ?', answer: 'Anglais' },
  { theme: 'Langue française', level: 8, question: 'Quel est le participe passé du verbe "coudre" ?', answer: 'Cousu' },
  { theme: 'Langue française', level: 9, question: 'Comment appelle-t-on la peur des mots longs ?', answer: 'Hippopotomonstrosesquippedaliophobie' },
  { theme: 'Langue française', level: 9, question: 'Quel mot français contient toutes les voyelles (et une seule fois chacune) ?', answer: 'Oiseau' },
  { theme: 'Langue française', level: 10, question: 'Quel est le seul mot de la langue française finissant par "g" qui se prononce ?', answer: 'Grog' },
  { theme: 'Langue française', level: 10, question: 'Quelle est la particularité du roman "La Disparition" de Georges Perec ?', answer: 'Sans la lettre E' },

  { theme: 'Inventions', level: 1, question: 'Qu\'a inventé Graham Bell ?', answer: 'Le téléphone' },
  { theme: 'Inventions', level: 1, question: 'Quelle invention permet de s\'éclairer avec de l\'électricité ?', answer: 'L\'ampoule' },
  { theme: 'Inventions', level: 2, question: 'Qu\'ont inventé les frères Lumière ?', answer: 'Le cinéma' },
  { theme: 'Inventions', level: 2, question: 'Quelle invention permet de voler dans les airs (frères Wright) ?', answer: 'L\'avion' },
  { theme: 'Inventions', level: 3, question: 'Qui a inventé l\'imprimerie en Europe ?', answer: 'Gutenberg' },
  { theme: 'Inventions', level: 3, question: 'Quel outil permet de voir les étoiles de près ?', answer: 'Le télescope' },
  { theme: 'Inventions', level: 4, question: 'Quelle invention de 1769 a lancé la révolution industrielle ?', answer: 'La machine à vapeur' },
  { theme: 'Inventions', level: 4, question: 'Qui a inventé la dynamite et créé un prix célèbre ?', answer: 'Alfred Nobel' },
  { theme: 'Inventions', level: 5, question: 'Quel pays a inventé la poudre à canon ?', answer: 'La Chine' },
  { theme: 'Inventions', level: 5, question: 'Qui a inventé le braille ?', answer: 'Louis Braille' },
  { theme: 'Inventions', level: 6, question: 'En quelle année a été inventé le Web (www) ?', answer: '1989' },
  { theme: 'Inventions', level: 6, question: 'Quelle invention de Marconi permet de transmettre du son sans fil ?', answer: 'La radio' },
  { theme: 'Inventions', level: 7, question: 'Qui a inventé le paratonnerre ?', answer: 'Benjamin Franklin' },
  { theme: 'Inventions', level: 7, question: 'Quel objet a été inventé par le Hongrois Ernő Rubik ?', answer: 'Le Rubik\'s Cube' },
  { theme: 'Inventions', level: 8, question: 'Qui a déposé le brevet du phonographe ?', answer: 'Thomas Edison' },
  { theme: 'Inventions', level: 8, question: 'Quelle invention médicale doit-on à Laennec ?', answer: 'Le stéthoscope' },
  { theme: 'Inventions', level: 9, question: 'Qui a inventé la pile électrique en 1800 ?', answer: 'Alessandro Volta' },
  { theme: 'Inventions', level: 9, question: 'Quel ingénieur allemand a inventé le moteur diesel ?', answer: 'Rudolf Diesel' },
  { theme: 'Inventions', level: 10, question: 'Qui a inventé le premier vaccin (contre la variole) ?', answer: 'Edward Jenner' },
  { theme: 'Inventions', level: 10, question: 'Quelle invention est attribuée à Laszlo Biro ?', answer: 'Le stylo à bille' },

  { theme: 'Géographie', level: 1, question: 'Quelle est la capitale de l\'Angleterre ?', answer: 'Londres' },
  { theme: 'Géographie', level: 2, question: 'Dans quel pays se trouve la Tour de Pise ?', answer: 'Italie' },
  { theme: 'Géographie', level: 3, question: 'Quel pays est aussi un continent ?', answer: 'Australie' },
  { theme: 'Géographie', level: 4, question: 'Quelle est la capitale de l\'Allemagne ?', answer: 'Berlin' },
  { theme: 'Géographie', level: 5, question: 'Quel est le plus long fleuve de France ?', answer: 'La Loire' },
  { theme: 'Géographie', level: 6, question: 'Quelle est la capitale du Portugal ?', answer: 'Lisbonne' },
  { theme: 'Géographie', level: 7, question: 'Quel pays a pour capitale Buenos Aires ?', answer: 'Argentine' },
  { theme: 'Géographie', level: 8, question: 'Quelle est la capitale de l\'Australie ?', answer: 'Canberra' },
  { theme: 'Géographie', level: 9, question: 'Dans quel pays se trouve le lac Baïkal ?', answer: 'Russie' },
  { theme: 'Géographie', level: 10, question: 'Quelle est la capitale de l\'Islande ?', answer: 'Reykjavik' },

  { theme: 'Histoire', level: 1, question: 'Quel monument a été construit pour l\'exposition universelle de 1889 ?', answer: 'La Tour Eiffel' },
  { theme: 'Histoire', level: 2, question: 'Qui a peint La Joconde ?', answer: 'Léonard de Vinci' },
  { theme: 'Histoire', level: 3, question: 'Quelle femme a été brûlée à Rouen en 1431 ?', answer: 'Jeanne d\'Arc' },
  { theme: 'Histoire', level: 4, question: 'Quel président américain a aboli l\'esclavage ?', answer: 'Abraham Lincoln' },
  { theme: 'Histoire', level: 5, question: 'En quelle année a eu lieu la Prise de la Bastille ?', answer: '1789' },
  { theme: 'Histoire', level: 6, question: 'Quel empereur romain a légalisé le christianisme ?', answer: 'Constantin' },
  { theme: 'Histoire', level: 7, question: 'Quel pays a attaqué Pearl Harbor en 1941 ?', answer: 'Japon' },
  { theme: 'Histoire', level: 8, question: 'Qui était le premier empereur de Rome ?', answer: 'Auguste' },
  { theme: 'Histoire', level: 9, question: 'Quel roi de France a régné 72 ans ?', answer: 'Louis XIV' },
  { theme: 'Histoire', level: 10, question: 'Quelle bataille marque la fin de l\'empire de Napoléon Ier en 1815 ?', answer: 'Waterloo' },

  { theme: 'Économie', level: 1, question: 'Quelle est la monnaie de l\'Europe ?', answer: 'L\'euro' },
  { theme: 'Économie', level: 2, question: 'Quelle est la monnaie des États-Unis ?', answer: 'Le dollar' },
  { theme: 'Économie', level: 3, question: 'Quel est le contraire de l\'achat ?', answer: 'La vente' },
  { theme: 'Économie', level: 4, question: 'Comment appelle-t-on une période de hausse générale des prix ?', answer: 'L\'inflation' },
  { theme: 'Économie', level: 5, question: 'Quelle monnaie est utilisée au Royaume-Uni ?', answer: 'La livre sterling' },
  { theme: 'Économie', level: 6, question: 'Que signifient les initiales PIB ?', answer: 'Produit Intérieur Brut' },
  { theme: 'Économie', level: 7, question: 'Comment appelle-t-on un marché où il n\'y a qu\'un seul vendeur ?', answer: 'Monopole' },
  { theme: 'Économie', level: 8, question: 'Quelle monnaie virtuelle a été créée par Satoshi Nakamoto ?', answer: 'Bitcoin' },
  { theme: 'Économie', level: 9, question: 'Qui a écrit "La Richesse des nations" (père du libéralisme) ?', answer: 'Adam Smith' },
  { theme: 'Économie', level: 10, question: 'Quelle crise boursière a eu lieu en 1929 ?', answer: 'Le Krach de 1929' },

  { theme: 'Politique', level: 1, question: 'Où habite le président de la France ?', answer: 'Au palais de l\'Élysée' },
  { theme: 'Politique', level: 2, question: 'Quelle couleur est associée à l\'écologie ?', answer: 'Vert' },
  { theme: 'Politique', level: 3, question: 'Combien de temps dure un mandat présidentiel en France ?', answer: '5 ans' },
  { theme: 'Politique', level: 4, question: 'Quel bâtiment abrite le Congrès américain ?', answer: 'Le Capitole' },
  { theme: 'Politique', level: 5, question: 'Qui est le chef du gouvernement en Allemagne ?', answer: 'Le chancelier' },
  { theme: 'Politique', level: 6, question: 'Combien d\'étoiles compte le drapeau européen ?', answer: '12' },
  { theme: 'Politique', level: 7, question: 'Quel texte fondamental régit les lois en France ?', answer: 'La Constitution' },
  { theme: 'Politique', level: 8, question: 'En quelle année les femmes ont-elles obtenu le droit de vote en France ?', answer: '1944' },
  { theme: 'Politique', level: 9, question: 'Qui a écrit "Le Prince" ?', answer: 'Machiavel' },
  { theme: 'Politique', level: 10, question: 'Quel président américain a démissionné suite au Watergate ?', answer: 'Richard Nixon' },

  { theme: 'Biologie', level: 1, question: 'Quel liquide rouge coule dans nos veines ?', answer: 'Le sang' },
  { theme: 'Biologie', level: 2, question: 'Quel organe nous permet de penser ?', answer: 'Le cerveau' },
  { theme: 'Biologie', level: 3, question: 'Combien de dents de lait a un enfant ?', answer: '20' },
  { theme: 'Biologie', level: 4, question: 'Quel est le nom scientifique des globules blancs ?', answer: 'Leucocytes' },
  { theme: 'Biologie', level: 5, question: 'Quelle maladie est transmise par le moustique tigre ?', answer: 'La dengue' },
  { theme: 'Biologie', level: 6, question: 'Quel organe produit la bile ?', answer: 'Le foie' },
  { theme: 'Biologie', level: 7, question: 'Combien de vertèbres cervicales possède une girafe ?', answer: '7' },
  { theme: 'Biologie', level: 8, question: 'Comment appelle-t-on les animaux qui mangent de tout ?', answer: 'Omnivores' },
  { theme: 'Biologie', level: 9, question: 'Quel est le muscle le plus volumineux du corps humain ?', answer: 'Le grand fessier' },
  { theme: 'Biologie', level: 10, question: 'Quelle est la seule cellule humaine visible à l\'œil nu ?', answer: 'L\'ovule' },

  { theme: 'Disney', level: 1, question: 'Quel animal est Mickey ?', answer: 'Une souris' },
  { theme: 'Disney', level: 2, question: 'Quelle princesse perd sa chaussure de verre ?', answer: 'Cendrillon' },
  { theme: 'Disney', level: 3, question: 'Comment s\'appelle le poisson clown héros du film ?', answer: 'Némo' },
  { theme: 'Disney', level: 4, question: 'Quel est le nom du tigre dans Le Livre de la Jungle ?', answer: 'Shere Khan' },
  { theme: 'Disney', level: 5, question: 'Quelle princesse a de très longs cheveux magiques ?', answer: 'Raiponce' },
  { theme: 'Disney', level: 6, question: 'Comment s\'appelle le cow-boy dans Toy Story ?', answer: 'Woody' },
  { theme: 'Disney', level: 7, question: 'Dans quelle ville se déroule Ratatouille ?', answer: 'Paris' },
  { theme: 'Disney', level: 8, question: 'Quel est le nom du crabe dans La Petite Sirène ?', answer: 'Sébastien' },
  { theme: 'Disney', level: 9, question: 'Quelle est la première princesse Disney (1937) ?', answer: 'Blanche-Neige' },
  { theme: 'Disney', level: 10, question: 'Quel est le nom complet de Wall-E ?', answer: 'Waste Allocation Load Lifter Earth-Class' },

  { theme: 'Harry Potter', level: 1, question: 'Quel animal est Hedwige ?', answer: 'Une chouette' },
  { theme: 'Harry Potter', level: 2, question: 'Comment s\'appelle l\'école des sorciers ?', answer: 'Poudlard' },
  { theme: 'Harry Potter', level: 3, question: 'Qui est le directeur de Poudlard au début de la saga ?', answer: 'Dumbledore' },
  { theme: 'Harry Potter', level: 4, question: 'Quelle est la maison de Harry Potter ?', answer: 'Gryffondor' },
  { theme: 'Harry Potter', level: 5, question: 'Quel sport pratiquent les sorciers sur des balais ?', answer: 'Le Quidditch' },
  { theme: 'Harry Potter', level: 6, question: 'Qui est le "Prince de Sang-Mêlé" ?', answer: 'Severus Rogue' },
  { theme: 'Harry Potter', level: 7, question: 'Comment s\'appelle le parrain de Harry ?', answer: 'Sirius Black' },
  { theme: 'Harry Potter', level: 8, question: 'Quel est le nom de l\'elfe de maison libéré par Harry ?', answer: 'Dobby' },
  { theme: 'Harry Potter', level: 9, question: 'Quel est le numéro de la chambre forte de Harry à Gringotts ?', answer: '687' },
  { theme: 'Harry Potter', level: 10, question: 'Qui a tué Bellatrix Lestrange ?', answer: 'Molly Weasley' },

  { theme: 'Chimie', level: 1, question: 'Quel est l\'état de l\'eau quand elle gèle ?', answer: 'Solide' },
  { theme: 'Chimie', level: 2, question: 'Quel gaz fait des bulles dans l\'eau gazeuse ?', answer: 'Le dioxyde de carbone' },
  { theme: 'Chimie', level: 3, question: 'Quel est le symbole chimique de l\'oxygène ?', answer: 'O' },
  { theme: 'Chimie', level: 4, question: 'Quel est le pH de l\'eau pure ?', answer: '7' },
  { theme: 'Chimie', level: 5, question: 'Quel métal est utilisé dans les thermomètres anciens ?', answer: 'Le mercure' },
  { theme: 'Chimie', level: 6, question: 'Quel atome a pour symbole C ?', answer: 'Le carbone' },
  { theme: 'Chimie', level: 7, question: 'Quel gaz est le plus léger ?', answer: 'L\'hydrogène' },
  { theme: 'Chimie', level: 8, question: 'Quel scientifique a créé le tableau périodique ?', answer: 'Mendeleïev' },
  { theme: 'Chimie', level: 9, question: 'Quel est le numéro atomique de l\'oxygène ?', answer: '8' },
  { theme: 'Chimie', level: 10, question: 'Quel acide est présent dans l\'estomac ?', answer: 'Acide chlorhydrique' },

  { theme: 'Mode', level: 1, question: 'Sur quelle partie du corps porte-t-on un chapeau ?', answer: 'La tête' },
  { theme: 'Mode', level: 2, question: 'Quel vêtement est le symbole des États-Unis (pantalon) ?', answer: 'Le jean' },
  { theme: 'Mode', level: 3, question: 'Quelle marque a un crocodile comme logo ?', answer: 'Lacoste' },
  { theme: 'Mode', level: 4, question: 'Qui a créé la petite robe noire ?', answer: 'Coco Chanel' },
  { theme: 'Mode', level: 5, question: 'Quelle est la capitale de la mode en Italie ?', answer: 'Milan' },
  { theme: 'Mode', level: 6, question: 'Quel couturier est célèbre pour ses semelles rouges ?', answer: 'Christian Louboutin' },
  { theme: 'Mode', level: 7, question: 'Quelle marque de luxe a pour logo deux G entrelacés ?', answer: 'Gucci' },
  { theme: 'Mode', level: 8, question: 'Qui est la rédactrice en chef célèbre de Vogue US ?', answer: 'Anna Wintour' },
  { theme: 'Mode', level: 9, question: 'Quel couturier a succédé à Christian Dior à sa mort ?', answer: 'Yves Saint Laurent' },
  { theme: 'Mode', level: 10, question: 'En quelle année a été créé le bikini ?', answer: '1946' },

  { theme: 'Philosophie', level: 1, question: 'Quel est l\'animal symbole de la sagesse ?', answer: 'La chouette' },
  { theme: 'Philosophie', level: 2, question: 'Qui a dit "Je pense donc je suis" ?', answer: 'Descartes' },
  { theme: 'Philosophie', level: 3, question: 'Quel philosophe grec a été condamné à boire la ciguë ?', answer: 'Socrate' },
  { theme: 'Philosophie', level: 4, question: 'Qui a écrit la Critique de la raison pure ?', answer: 'Kant' },
  { theme: 'Philosophie', level: 5, question: 'Quel philosophe a écrit "L\'Enfer, c\'est les autres" ?', answer: 'Sartre' },
  { theme: 'Philosophie', level: 6, question: 'Qui est l\'auteur du "Mythe de la caverne" ?', answer: 'Platon' },
  { theme: 'Philosophie', level: 7, question: 'Quel philosophe est associé au concept de "Surhomme" ?', answer: 'Nietzsche' },
  { theme: 'Philosophie', level: 8, question: 'Qui a dit "L\'homme est un loup pour l\'homme" ?', answer: 'Hobbes' },
  { theme: 'Philosophie', level: 9, question: 'De quel pays est originaire Confucius ?', answer: 'Chine' },
  { theme: 'Philosophie', level: 10, question: 'Quel philosophe a écrit "Ainsi parlait Zarathoustra" ?', answer: 'Nietzsche' },

  { theme: 'Architecture', level: 1, question: 'De quoi sont faites les Pyramides d\'Égypte ?', answer: 'De pierre' },
  { theme: 'Architecture', level: 2, question: 'Quel monument de New York porte une torche ?', answer: 'La Statue de la Liberté' },
  { theme: 'Architecture', level: 3, question: 'Quel type d\'arche est pointu (style gothique) ?', answer: 'L\'arc brisé' },
  { theme: 'Architecture', level: 4, question: 'Qui a conçu la pyramide du Louvre ?', answer: 'I.M. Pei' },
  { theme: 'Architecture', level: 5, question: 'Dans quelle ville se trouve le Colisée ?', answer: 'Rome' },
  { theme: 'Architecture', level: 6, question: 'Quel architecte espagnol a conçu la Sagrada Família ?', answer: 'Gaudí' },
  { theme: 'Architecture', level: 7, question: 'Quel style architectural caractérise Notre-Dame de Paris ?', answer: 'Gothique' },
  { theme: 'Architecture', level: 8, question: 'Quel architecte français est connu pour le béton armé et la Cité radieuse ?', answer: 'Le Corbusier' },
  { theme: 'Architecture', level: 9, question: 'Quel est le plus haut gratte-ciel du monde (en 2023) ?', answer: 'Burj Khalifa' },
  { theme: 'Architecture', level: 10, question: 'Quel architecte a conçu le musée Guggenheim de Bilbao ?', answer: 'Frank Gehry' }
];
